from sqlite3 import OperationalError

from playhouse.migrate import SqliteMigrator

from .models import (BaseChild, Context, Child, OOHRecord, RecognizedTribe, SecondParent, Removal1993, Removal2020,
                     LivingArrangement, PermanencyPlan, PeriodicReview, PermanencyHearing, CaseVisit,
                     ARecord, Export)
from .tables import (database, BaseChildTable, ConfigTable, ContextTable, StateTable, TribeTable, TribeStateTable,
                     Version)
from .migrations import *

DATABASE_VERSION: int = 0


def open_database(database_name: str):
    close_database()
    database.init(database_name)
    database.connect()
    apply_migrations(database.connection())


def close_database():
    if not database.is_closed():
        database.close()


def create_tables():
    database.create_tables(
        [DatabaseVersion, BaseChildTable, ConfigTable, ContextTable, StateTable, TribeTable, TribeStateTable]
    )

    # print(BaseChildTable.create_table())
    bootstrap_states()
    bootstrap_tribes()
    bootstrap_fips_codes()


def apply_migrations(connection) -> None:
    cursor = connection.cursor()
    try:
        result = cursor.execute('SELECT database_version FROM version WHERE id=1')
        current_version = result.fetchone()[0]
    except OperationalError as oe:
        _do_migration(0)
        current_version = 0

    if DATABASE_VERSION > current_version:
        while current_version := current_version + 1 <= DATABASE_VERSION:
            _do_migration(current_version)

    config = ConfigTable.get_by_id(1)
    config.database_version = DATABASE_VERSION
    config.save()


def _do_migration(version: int) -> None:
    migrator = SqliteMigrator(database)
    func_name = f"migration_{version}"
    if func_name in globals() and callable(globals()[func_name]):
        func = globals()[func_name]
        func(migrator)


def bootstrap_states():
    data = (("AL", "Alabama"), ("AK", "Alaska"), ("AS", "American Samoa"), ("AZ", "Arizona"), ("AR", "Arkansas"),
            ("CA", "California"), ("CO", "Colorado"), ("CT", "Connecticut"), ("DE", "Delaware"),
            ("DC", "District of Columbia"),
            ("FL", "Florida"), ("GA", "Georgia"), ("GU", "Guam"), ("HI", "Hawaii"), ("ID", "Idaho"), ("IL", "Illinois"),
            ("IN", "Indiana"), ("IA", "Iowa"), ("KS", "Kansas"), ("KY", "Kentucky"), ("LA", "Louisiana"),
            ("ME", "Maine"),
            ("MD", "Maryland"), ("MA", "Massachusetts"), ("MI", "Michigan"), ("MN", "Minnesota"), ("MS", "Mississippi"),
            ("MO", "Missouri"), ("MT", "Montana"), ("NE", "Nebraska"), ("NV", "Nevada"), ("NH", "New Hampshire"),
            ("NJ", "New Jersey"), ("NM", "New Mexico"), ("NY", "New York"), ("NC", "North Carolina"),
            ("ND", "North Dakota"), ("MP", "Northern Mariana Islands"), ("OH", "Ohio"), ("OK", "Oklahoma"),
            ("OR", "Oregon"),
            ("PA", "Pennsylvania"), ("PR", "Puerto Rico"), ("RI", "Rhode Island"), ("SC", "South Carolina"),
            ("SD", "South Dakota"), ("TN", "Tennessee"), ("TX", "Texas"), ("UT", "Utah"), ("VT", "Vermont"),
            ("VI", "U.S. Virgin Islands"), ("VA", "Virginia"), ("WA", "Washington"), ("WV", "West Virginia"),
            ("WI", "Wisconsin"), ("WY", "Wyoming"),
            )
    for code, name in data:
        StateTable.get_or_create(code=code, name=name)


def bootstrap_tribes():
    data = [
        ("Agdaagux Tribe of King Cove", "341", ("AK",)),
        ("Akiachak Native Community", "343", ("AK",)),
        ("Akiak Native Community", "344", ("AK",)),
        ("Alatna Village", "347", ("AK",)),
        ("Algaaciq Native Village (St. Mary's)", "349", ("AK",)),
        ("Allakaket Village", "350", ("AK",)),
        ("Alutiiq Tribe of Old Harbor", "495", ("AK",)),
        ("Angoon Community Association", "354", ("AK",)),
        ("Anvik Village", "356", ("AK",)),
        ("Arctic Village (See Native Village of Venetie Tribal Government)", "357", ("AK",)),
        ("Asa'carsarmiut Tribe", "358", ("AK",)),
        ("Atqasuk Village (Atkasook)", "361", ("AK",)),
        ("Beaver Village", "363", ("AK",)),
        ("Birch Creek Tribe", "366", ("AK",)),
        ("Central Council of the Tlingit & Haida Indian Tribes", "551", ("AK",)),
        ("Chalkyitsik Village", "371", ("AK",)),
        ("Cheesh-Na Tribe", "372", ("AK",)),
        ("Chevak Native Village", "374", ("AK",)),
        ("Chickaloon Native Village", "375", ("AK",)),
        ("Chignik Bay Tribal Council", "376", ("AK",)),
        ("Chignik Lake Village", "378", ("AK",)),
        ("Chilkat Indian Village (Klukwan)", "379", ("AK",)),
        ("Chilkoot Indian Association (Haines)", "380", ("AK",)),
        ("Chinik Eskimo Community (Golovin)", "381", ("AK",)),
        ("Chuloonawick Native Village", "384", ("AK",)),
        ("Circle Native Community", "385", ("AK",)),
        ("Craig Tribal Association", "388", ("AK",)),
        ("Curyung Tribal Council", "390", ("AK",)),
        ("Douglas Indian Association", "394", ("AK",)),
        ("Egegik Village", "397", ("AK",)),
        ("Eklutna Native Village", "398", ("AK",)),
        ("Emmonak Village", "402", ("AK",)),
        ("Evansville Village (aka Bettles Field)", "403", ("AK",)),
        ("Galena Village (aka Louden Village)", "408", ("AK",)),
        ("Gulkana Village Council", "413", ("AK",)),
        ("Healy Lake Village", "415", ("AK",)),
        ("Holy Cross Tribe", "416", ("AK",)),
        ("Hoonah Indian Association", "417", ("AK",)),
        ("Hughes Village", "419", ("AK",)),
        ("Huslia Village", "420", ("AK",)),
        ("Hydaburg Cooperative Association", "421", ("AK",)),
        ("Igiugig Village", "422", ("AK",)),
        ("Inupiat Community of the Arctic Slope", "424", ("AK",)),
        ("Iqugmiut Traditional Council", "425", ("AK",)),
        ("Ivanof Bay Tribe", "426", ("AK",)),
        ("Kaguyak Village", "427", ("AK",)),
        ("Kaktovik Village (aka Barter Island)", "429", ("AK",)),
        ("Kasigluk Traditional Elders Council", "435", ("AK",)),
        ("Kenaitze Indian Tribe", "436", ("AK",)),
        ("Ketchikan Indian Corporation", "437", ("AK",)),
        ("King Island Native Community", "439", ("AK",)),
        ("King Salmon Tribe", "440", ("AK",)),
        ("Klawock Cooperative Association", "443", ("AK",)),
        ("Knik Tribe", "445", ("AK",)),
        ("Kokhanok Village", "447", ("AK",)),
        ("Koyukuk Native Village", "452", ("AK",)),
        ("Levelock Village", "457", ("AK",)),
        ("Lime Village", "458", ("AK",)),
        ("Manley Hot Springs Village", "460", ("AK",)),
        ("Manokotak Village", "461", ("AK",)),
        ("McGrath Native Village", "464", ("AK",)),
        ("Mentasta Traditional Council", "466", ("AK",)),
        ("Metlakatla Indian Community, Annette Island Reserve", "467", ("AK",)),
        ("Naknek Native Village", "469", ("AK",)),
        ("Native Village of Afognak", "340", ("AK",)),
        ("Native Village of Akhiok", "342", ("AK",)),
        ("Native Village of Akutan", "345", ("AK",)),
        ("Native Village of Aleknagik", "348", ("AK",)),
        ("Native Village of Ambler", "351", ("AK",)),
        ("Native Village of Atka", "359", ("AK",)),
        ("Native Village of Atqasuk", "361", ("AK",)),
        ("Native Village of Barrow Inupiat Traditional Government", "362", ("AK",)),
        ("Native Village of Belkofski", "364", ("AK",)),
        ("Native Village of Brevig Mission", "367", ("AK",)),
        ("Native Village of Buckland", "368", ("AK",)),
        ("Native Village of Cantwell", "369", ("AK",)),
        ("Native Village of Chenega (aka Chanega)", "370", ("AK",)),
        ("Native Village of Chignik Lagoon", "377", ("AK",)),
        ("Native Village of Chitina", "382", ("AK",)),
        ("Native Village of Chuathbaluk (Russian Mission, Kuskokwim)", "383", ("AK",)),
        ("Native Village of Council", "387", ("AK",)),
        ("Native Village of Deering", "391", ("AK",)),
        ("Native Village of Diomede (aka Inalik)", "392", ("AK",)),
        ("Native Village of Eagle", "395", ("AK",)),
        ("Native Village of Eek", "396", ("AK",)),
        ("Native Village of Ekuk", "399", ("AK",)),
        ("Native Village of Ekwok", "400", ("AK",)),
        ("Native Village of Elim", "401", ("AK",)),
        ("Native Village of Eyak (Cordova)", "404", ("AK",)),
        ("Native Village of False Pass", "405", ("AK",)),
        ("Native Village of Fort Yukon", "406", ("AK",)),
        ("Native Village of Gakona", "407", ("AK",)),
        ("Native Village of Gambell", "409", ("AK",)),
        ("Native Village of Georgetown", "410", ("AK",)),
        ("Native Village of Goodnews Bay", "411", ("AK",)),
        ("Native Village of Hamilton", "414", ("AK",)),
        ("Native Village of Hooper Bay", "418", ("AK",)),
        ("Native Village of Kanatak", "432", ("AK",)),
        ("Native Village of Karluk", "433", ("AK",)),
        ("Native Village of Kiana", "438", ("AK",)),
        ("Native Village of Kipnuk", "441", ("AK",)),
        ("Native Village of Kivalina", "442", ("AK",)),
        ("Native Village of Kluti Kaah (aka Copper Center)", "444", ("AK",)),
        ("Native Village of Kobuk", "446", ("AK",)),
        ("Native Village of Kongiganak", "448", ("AK",)),
        ("Native Village of Kotzebue", "450", ("AK",)),
        ("Native Village of Koyuk", "451", ("AK",)),
        ("Native Village of Kwigillingok", "454", ("AK",)),
        ("Native Village of Kwinhagak (aka Quinhagak)", "455", ("AK",)),
        ("Native Village of Larsen Bay", "456", ("AK",)),
        ("Native Village of Marshall (aka Fortuna Ledge)", "462", ("AK",)),
        ("Native Village of Mary's Igloo", "463", ("AK",)),
        ("Native Village of Mekoryuk", "465", ("AK",)),
        ("Native Village of Minto", "468", ("AK",)),
        ("Native Village of Nanwalek (aka English Bay)", "470", ("AK",)),
        ("Native Village of Napaimute", "471", ("AK",)),
        ("Native Village of Napakiak", "472", ("AK",)),
        ("Native Village of Napaskiak", "473", ("AK",)),
        ("Native Village of Nelson Lagoon", "474", ("AK",)),
        ("Native Village of Nightmute", "480", ("AK",)),
        ("Native Village of Nikolski", "482", ("AK",)),
        ("Native Village of Noatak", "484", ("AK",)),
        ("Native Village of Nuiqsut (aka Nooiksut)", "489", ("AK",)),
        ("Native Village of Nunam Iqua", "492", ("AK",)),
        ("Native Village of Nunapitchuk", "493", ("AK",)),
        ("Native Village of Ouzinkie", "498", ("AK",)),
        ("Native Village of Paimiut", "499", ("AK",)),
        ("Native Village of Perryville", "502", ("AK",)),
        ("Native Village of Pilot Point", "504", ("AK",)),
        ("Native Village of Point Hope", "508", ("AK",)),
        ("Native Village of Point Lay", "509", ("AK",)),
        ("Native Village of Port Graham", "510", ("AK",)),
        ("Native Village of Port Heiden", "511", ("AK",)),
        ("Native Village of Port Lions", "512", ("AK",)),
        ("Native Village of Ruby", "519", ("AK",)),
        ("Native Village of Saint Michael", "521", ("AK",)),
        ("Native Village of Savoonga", "524", ("AK",)),
        ("Native Village of Scammon Bay", "526", ("AK",)),
        ("Native Village of Selawik", "527", ("AK",)),
        ("Native Village of Shaktoolik", "530", ("AK",)),
        ("Native Village of Shishmaref", "531", ("AK",)),
        ("Native Village of Shungnak", "532", ("AK",)),
        ("Native Village of Stevens", "539", ("AK",)),
        ("Native Village of Tanacross", "543", ("AK",)),
        ("Native Village of Tanana", "544", ("AK",)),
        ("Native Village of Tatitlek", "546", ("AK",)),
        ("Native Village of Tazlina", "547", ("AK",)),
        ("Native Village of Teller", "549", ("AK",)),
        ("Native Village of Tetlin", "550", ("AK",)),
        ("Native Village of Tuntutuliak", "554", ("AK",)),
        ("Native Village of Tununak", "555", ("AK",)),
        ("Native Village of Tyonek", "557", ("AK",)),
        ("Native Village of Unalakleet", "560", ("AK",)),
        ("Native Village of Unga", "561", ("AK",)),
        ("Native Village of Venetie Tribal Government (Arctic Village and Village of Venetie)", "563", ("AK",)),
        ("Native Village of Wales", "565", ("AK",)),
        ("Native Village of White Mountain", "566", ("AK",)),
        ("Nenana Native Association", "475", ("AK",)),
        ("New Koliganek Village Council", "476", ("AK",)),
        ("New Stuyahok Village", "477", ("AK",)),
        ("Newhalen Village", "478", ("AK",)),
        ("Newtok Village", "479", ("AK",)),
        ("Nikolai Village", "481", ("AK",)),
        ("Ninilchik Village", "483", ("AK",)),
        ("Nome Eskimo Community", "485", ("AK",)),
        ("Nondalton Village", "486", ("AK",)),
        ("Noorvik Native Community", "487", ("AK",)),
        ("Northway Village", "488", ("AK",)),
        ("Nulato Village", "490", ("AK",)),
        ("Nunakauyarmiut Tribe", "491", ("AK",)),
        ("Organized Village of Grayling (aka Holikachuk)", "412", ("AK",)),
        ("Organized Village of Kake", "428", ("AK",)),
        ("Organized Village of Kasaan", "434", ("AK",)),
        ("Organized Village of Kwethluk", "453", ("AK",)),
        ("Organized Village of Saxman", "525", ("AK",)),
        ("Orutsararmiut Traditional Native Council", "496", ("AK",)),
        ("Oscarville Traditional Village", "497", ("AK",)),
        ("Pauloff Harbor Village", "500", ("AK",)),
        ("Pedro Bay Village", "501", ("AK",)),
        ("Petersburg Indian Association", "503", ("AK",)),
        ("Pilot Station Traditional Village", "505", ("AK",)),
        ("Pitka's Point Traditional Council", "506", ("AK",)),
        ("Platinum Traditional Village", "507", ("AK",)),
        ("Portage Creek Village (aka Ohgsenakale)", "513", ("AK",)),
        ("Pribilof Islands Aleut Communities of St. Paul & St. George Islands", "514", ("AK",)),
        ("Qagan Tayagungin Tribe of Sand Point", "515", ("AK",)),
        ("Qawalangin Tribe of Unalaska", "516", ("AK",)),
        ("Rampart Village", "517", ("AK",)),
        (
            "Saint George Island (See Pribilof Islands Aleut Communities of St. Paul & St. George Islands)", "520",
            ("AK",)),
        ("Saint Paul Island (See Pribilof Islands Aleut Communities of St. Paul & St. George Islands)", "522", ("AK",)),
        ("Salamatof Tribe", "523", ("AK",)),
        ("Seldovia Village Tribe", "528", ("AK",)),
        ("Shageluk Native Village", "529", ("AK",)),
        ("Sitka Tribe of Alaska", "533", ("AK",)),
        ("Skagway Village", "534", ("AK",)),
        ("South Naknek Village", "537", ("AK",)),
        ("Stebbins Community Association", "538", ("AK",)),
        ("Sun'aq Tribe of Kodiak", "541", ("AK",)),
        ("Takotna Village", "542", ("AK",)),
        ("Tangirnaq Native Village", "545", ("AK",)),
        ("Telida Village", "548", ("AK",)),
        ("Traditional Village of Togiak", "552", ("AK",)),
        ("Tuluksak Native Community", "553", ("AK",)),
        ("Twin Hills Village", "556", ("AK",)),
        ("Ugashik Village", "558", ("AK",)),
        ("Umkumiut Native Village", "559", ("AK",)),
        ("Village of Alakanuk", "346", ("AK",)),
        ("Village of Anaktuvuk Pass", "352", ("AK",)),
        ("Village of Aniak", "355", ("AK",)),
        ("Village of Atmautluak", "360", ("AK",)),
        ("Village of Bill Moore's Slough", "365", ("AK",)),
        ("Village of Chefornak", "373", ("AK",)),
        ("Village of Clarks Point", "386", ("AK",)),
        ("Village of Crooked Creek", "389", ("AK",)),
        ("Village of Dot Lake", "393", ("AK",)),
        ("Village of Iliamna", "423", ("AK",)),
        ("Village of Kalskag", "430", ("AK",)),
        ("Village of Kaltag", "431", ("AK",)),
        ("Village of Kotlik", "449", ("AK",)),
        ("Village of Lower Kalskag", "459", ("AK",)),
        ("Village of Ohogamiut", "494", ("AK",)),
        ("Village of Red Devil", "518", ("AK",)),
        ("Village of Sleetmute", "535", ("AK",)),
        ("Village of Solomon", "536", ("AK",)),
        ("Village of Stony River", "540", ("AK",)),
        ("Village of Venetie (See Native Village of Venetie Tribal Government)", "562", ("AK",)),
        ("Village of Wainwright", "564", ("AK",)),
        ("Wrangell Cooperative Association", "567", ("AK",)),
        ("Yakutat Tlingit Tribe", "568", ("AK",)),
        ("Yupiit of Andreafski", "353", ("AK",)),
        ("Poarch Band of Creeks", "204", ("AL", "FL",)),
        ("Ak-Chin Indian Community", "3", ("AZ",)),
        ("Cocopah Tribe of Arizona", "48", ("AZ",)),
        ("Fort McDowell Yavapai Nation, Arizona", "90", ("AZ",)),
        ("Gila River Indian Community of the Gila River Indian Reservation, Arizona", "93", ("AZ",)),
        ("Havasupai Tribe of the Havasupai Reservation, Arizona", "100", ("AZ",)),
        ("Hopi Tribe of Arizona", "104", ("AZ",)),
        ("Hualapai Indian Tribe of the Hualapai Indian Reservation, Arizona", "107", ("AZ",)),
        ("Kaibab Band of Paiute Indians of the Kaibab Indian Reservation, Arizona", "118", ("AZ",)),
        ("Pascua Yaqui Tribe of Arizona", "193", ("AZ",)),
        ("Salt River Pima-Maricopa Indian Community of the Salt River Reservation, Arizona", "252", ("AZ",)),
        ("San Carlos Apache Tribe of the San Carlos Reservation, Arizona", "254", ("AZ",)),
        ("San Juan Southern Paiute Tribe of Arizona", "255", ("AZ",)),
        ("Tohono O'odham Nation of Arizona", "302", ("AZ",)),
        ("Tonto Apache Tribe of Arizona", "305", ("AZ",)),
        ("White Mountain Apache Tribe of the Fort Apache Reservation, Arizona", "324", ("AZ",)),
        ("Yavapai-Apache Nation of the Camp Verde Indian Reservation, Arizona", "332", ("AZ",)),
        ("Yavapai-Prescott Indian Tribe", "333", ("AZ",)),
        ("Colorado River Indian Tribes of the Colorado River Indian Reservation, Arizona and California", "51",
         ("AZ", "CA",)),
        ("Quechan Tribe of the Fort Yuma Indian Reservation, California & Arizona", "232", ("AZ", "CA",)),
        ("Fort Mojave Indian Tribe of Arizona, California & Nevada", "91", ("AZ", "CA", "NV",)),
        ("Zuni Tribe of the Zuni Reservation, New Mexico", "339", ("AZ", "NM",)),
        ("Fort Sill Apache Tribe of Oklahoma", "92", ("AZ", "NM", "OK",)),
        ("Navajo Nation, Arizona, New Mexico & Utah", "171", ("AZ", "NM", "UT",)),
        ("Agua Caliente Band of Cahuilla Indians of the Agua Caliente Indian Reservation, California", "2", ("CA",)),
        ("Alturas Indian Rancheria, California", "6", ("CA",)),
        ("Augustine Band of Cahuilla Indians, California", "11", ("CA",)),
        ("Bear River Band of the Rohnerville Rancheria, California", "14", ("CA",)),
        ("Berry Creek Rancheria of Maidu Indians of California", "15", ("CA",)),
        ("Big Lagoon Rancheria, California", "16", ("CA",)),
        ("Big Pine Paiute Tribe of the Owens Valley", "17", ("CA",)),
        ("Big Sandy Rancheria of Western Mono Indians of California", "18", ("CA",)),
        ("Big Valley Band of Pomo Indians of the Big Valley Rancheria, California", "19", ("CA",)),
        ("Bishop Paiute Tribe", "189", ("CA",)),
        ("Blue Lake Rancheria, California", "21", ("CA",)),
        ("Bridgeport Indian Colony", "22", ("CA",)),
        ("Buena Vista Rancheria of Me-Wuk Indians of California", "23", ("CA",)),
        ("Cabazon Band of Mission Indians, California", "25", ("CA",)),
        ("Cachil DeHe Band of Wintun Indians of the Colusa Indian Community of the Colusa Rancheria, California", "26",
         ("CA",)),
        ("Cahto Tribe of the Laytonville Rancheria", "29", ("CA",)),
        ("Cahuilla Band of Indians", "28", ("CA",)),
        ("California Valley Miwok Tribe, California", "30", ("CA",)),
        ("Campo Band of Diegueno Mission Indians of the Campo Indian Reservation, California", "31", ("CA",)),
        (
            "Capitan Grande Band of Diegueno Mission Indians of California (Barona Group of Capitan Grande Band of Mission Indians of the Barona Reservation, California; Viejas (Baron Long) Group of Capitan Grande Band of Mission Indians of the Viejas Reservation, California)",
            "32", ("CA",)),
        ("Cedarville Rancheria, California", "35", ("CA",)),
        ("Chemehuevi Indian Tribe of the Chemehuevi Reservation, California", "36", ("CA",)),
        ("Cher-Ae Heights Indian Community of the Trinidad Rancheria, California", "37", ("CA",)),
        ("Chicken Ranch Rancheria of Me-Wuk Indians of California", "42", ("CA",)),
        ("Cloverdale Rancheria of Pomo Indians of California", "47", ("CA",)),
        ("Cold Springs Rancheria of Mono Indians of California", "50", ("CA",)),
        ("Coyote Valley Band of Pomo Indians of California", "68", ("CA",)),
        ("Dry Creek Rancheria Band of Pomo Indians, California", "74", ("CA",)),
        ("Elem Indian Colony of Pomo Indians of the Sulphur Bank Rancheria, California", "78", ("CA",)),
        ("Elk Valley Rancheria, California", "79", ("CA",)),
        ("Enterprise Rancheria of Maidu Indians of California", "81", ("CA",)),
        ("Ewiiaapaayp Band of Kumeyaay Indians, California", "82", ("CA",)),
        ("Federated Indians of Graton Rancheria, California", "83", ("CA",)),
        ("Fort Bidwell Indian Community of the Fort Bidwell Reservation of California", "87", ("CA",)),
        ("Fort Independence Indian Community of Paiute Indians of the Fort Independence Reservation, California", "88",
         ("CA",)),
        ("Greenville Rancheria", "95", ("CA",)),
        ("Grindstone Indian Rancheria of Wintun-Wailaki Indians of California", "96", ("CA",)),
        ("Guidiville Rancheria of California", "97", ("CA",)),
        ("Habematolel Pomo of Upper Lake, California", "98", ("CA",)),
        ("Hoopa Valley Tribe, California", "103", ("CA",)),
        ("Hopland Band of Pomo Indians, California", "105", ("CA",)),
        ("Iipay Nation of Santa Ysabel, California", "108", ("CA",)),
        ("Inaja Band of Diegueno Mission Indians of the Inaja and Cosmit Reservation, California", "109", ("CA",)),
        ("Ione Band of Miwok Indians of California", "110", ("CA",)),
        ("Jackson Band of Miwuk Indians", "113", ("CA",)),
        ("Jamul Indian Village of California", "115", ("CA",)),
        ("Karuk Tribe", "120", ("CA",)),
        ("Kashia Band of Pomo Indians of the Stewarts Point Rancheria, California", "121", ("CA",)),
        ("Kletsel Dehe Band of Wintun Indians", "64", ("CA",)),
        ("Koi Nation of Northern California", "140", ("CA",)),
        ("La Jolla Band of Luiseno Indians, California", "132", ("CA",)),
        ("La Posta Band of Diegueno Mission Indians of the La Posta Indian Reservation, California", "133", ("CA",)),
        ("Lone Pine Paiute-Shoshone Tribe", "191", ("CA",)),
        ("Los Coyotes Band of Cahuilla and Cupeno Indians, California", "141", ("CA",)),
        ("Lytton Rancheria of California", "147", ("CA",)),
        ("Manchester Band of Pomo Indians of the Manchester Rancheria, California", "149", ("CA",)),
        ("Manzanita Band of Diegueno Mission Indians of the Manzanita Reservation, California", "150", ("CA",)),
        ("Mechoopda Indian Tribe of Chico Rancheria, California", "154", ("CA",)),
        ("Mesa Grande Band of Diegueno Mission Indians of the Mesa Grande Reservation, California", "156", ("CA",)),
        ("Middletown Rancheria of Pomo Indians of California", "160", ("CA",)),
        ("Mooretown Rancheria of Maidu Indians of California", "166", ("CA",)),
        ("Morongo Band of Mission Indians, California", "167", ("CA",)),
        ("Northfork Rancheria of Mono Indians of California", "176", ("CA",)),
        ("Pala Band of Mission Indians", "192", ("CA",)),
        ("Paskenta Band of Nomlaki Indians of California", "194", ("CA",)),
        ("Pauma Band of Luiseno Mission Indians of the Pauma & Yuima Reservation, California", "196", ("CA",)),
        ("Pechanga Band of Luiseno Mission Indians of the Pechanga Reservation, California", "198", ("CA",)),
        ("Picayune Rancheria of Chukchansi Indians of California", "201", ("CA",)),
        ("Pinoleville Pomo Nation, California", "202", ("CA",)),
        (
            "Pit River Tribe, California (includes XL Ranch, Big Bend, Likely, Lookout, Montgomery Creek and Roaring Creek Rancherias)",
            "203", ("CA",)),
        ("Potter Valley Tribe, California", "209", ("CA",)),
        ("Quartz Valley Indian Community of the Quartz Valley Reservation of California", "231", ("CA",)),
        ("Ramona Band of Cahuilla, California", "235", ("CA",)),
        ("Redding Rancheria, California", "238", ("CA",)),
        ("Redwood Valley or Little River Band of Pomo Indians of the Redwood Valley Rancheria California", "239",
         ("CA",)),
        ("Resighini Rancheria, California", "241", ("CA",)),
        ("Rincon Band of Luiseno Mission Indians of Rincon Reservation, California", "242", ("CA",)),
        ("Robinson Rancheria", "243", ("CA",)),
        ("Round Valley Indian Tribes, Round Valley Reservation, California", "245", ("CA",)),
        ("San Pasqual Band of Diegueno Mission Indians of California", "257", ("CA",)),
        ("Santa Rosa Band of Cahuilla Indians, California", "259", ("CA",)),
        ("Santa Rosa Indian Community of the Santa Rosa Rancheria, California", "258", ("CA",)),
        ("Santa Ynez Band of Chumash Mission Indians of the Santa Ynez Reservation, California", "260", ("CA",)),
        ("Scotts Valley Band of Pomo Indians of California", "264", ("CA",)),
        ("Sherwood Valley Rancheria of Pomo Indians of California", "271", ("CA",)),
        ("Shingle Springs Band of Miwok Indians, Shingle Springs Rancheria (Verona Tract), California", "272", ("CA",)),
        ("Soboba Band of Luiseno Indians, California", "283", ("CA",)),
        ("Susanville Indian Rancheria, California", "294", ("CA",)),
        ("Sycuan Band of the Kumeyaay Nation", "296", ("CA",)),
        ("Table Mountain Rancheria", "297", ("CA",)),
        ("Tejon Indian Tribe", "298", ("CA",)),
        ("Tolowa Dee-ni' Nation", "281", ("CA",)),
        ("Torres Martinez Desert Cahuilla Indians, California", "306", ("CA",)),
        ("Tule River Indian Tribe of the Tule River Reservation, California", "307", ("CA",)),
        ("Tuolumne Band of Me-Wuk Indians of the Tuolumne Rancheria of California", "310", ("CA",)),
        ("Twenty-Nine Palms Band of Mission Indians of California", "313", ("CA",)),
        ("United Auburn Indian Community of the Auburn Rancheria of California", "314", ("CA",)),
        ("Utu Utu Gwaitu Paiute Tribe of the Benton Paiute Reservation, California", "320", ("CA",)),
        ("Wilton Rancheria, California", "326", ("CA",)),
        ("Wiyot Tribe, California", "329", ("CA",)),
        ("Yocha Dehe Wintun Nation, California", "335", ("CA",)),
        ("Yuhaaviatam of San Manuel Nation", "256", ("CA",)),
        ("Yurok Tribe of the Yurok Reservation, California", "338", ("CA",)),
        ("Timbisha Shoshone Tribe", "71", ("CA", "NV",)),
        (
            "Washoe Tribe of Nevada & California (Carson Colony, Dresslerville Colony, Woodfords Community, Stewart Community & Washoe Ranches)",
            "323", ("CA", "NV",)),
        ("Southern Ute Indian Tribe of the Southern Ute Reservation, Colorado", "285", ("CO",)),
        ("Ute Mountain Ute Tribe", "319", ("CO", "NM",)),
        ("Mashantucket Pequot Indian Tribe", "151", ("CT",)),
        ("Mohegan Tribe of Indians of Connecticut", "165", ("CT",)),
        ("Miccosukee Tribe of Indians", "159", ("FL",)),
        ("Seminole Tribe of Florida", "266", ("FL",)),
        ("Sac & Fox Tribe of the Mississippi in Iowa", "246", ("IA",)),
        ("Omaha Tribe of Nebraska", "181", ("IA", "NE",)),
        ("Ponca Tribe of Nebraska", "207", ("IA", "NE",)),
        ("Winnebago Tribe of Nebraska", "327", ("IA", "NE",)),
        ("Kootenai Tribe of Idaho", "131", ("ID",)),
        ("Nez Perce Tribe", "172", ("ID",)),
        ("Shoshone-Bannock Tribes of the Fort Hall Reservation", "276", ("ID",)),
        ("Coeur D'Alene Tribe", "49", ("ID", "MT",)),
        ("Shoshone-Paiute Tribes of the Duck Valley Reservation, Nevada", "277", ("ID", "NV",)),
        ("Pokagon Band of Potawatomi Indians, Michigan and Indiana", "205", ("IN", "MI",)),
        ("Kickapoo Tribe of Indians of the Kickapoo Reservation in Kansas", "126", ("KS",)),
        ("Prairie Band Potawatomi Nation", "210", ("KS",)),
        ("Iowa Tribe of Kansas and Nebraska", "111", ("KS", "NE",)),
        ("Sac & Fox Nation of Missouri in Kansas and Nebraska", "247", ("KS", "NE",)),
        ("Quapaw Nation", "230", ("KS", "OK",)),
        ("The Muscogee (Creek) Nation", "169", ("KS", "OK",)),
        ("Wyandotte Nation", "330", ("KS", "OK",)),
        ("Chitimacha Tribe of Louisiana", "44", ("LA",)),
        ("Coushatta Tribe of Louisiana", "65", ("LA",)),
        ("Jena Band of Choctaw Indians", "116", ("LA",)),
        ("Tunica-Biloxi Indian Tribe", "309", ("LA",)),
        ("Mashpee Wampanoag Tribe", "152", ("MA",)),
        ("Wampanoag Tribe of Gay Head (Aquinnah)", "322", ("MA",)),
        ("Mi’kmaq Nation", "9", ("ME",)),
        ("Houlton Band of Maliseet Indians", "106", ("ME",)),
        ("Passamaquoddy Tribe", "195", ("ME",)),
        ("Penobscot Nation", "199", ("ME",)),
        ("Bay Mills Indian Community, Michigan", "13", ("MI",)),
        ("Grand Traverse Band of Ottawa and Chippewa Indians, Michigan", "94", ("MI",)),
        ("Hannahville Indian Community, Michigan", "99", ("MI",)),
        ("Keweenaw Bay Indian Community, Michigan", "124", ("MI",)),
        ("Lac Vieux Desert Band of Lake Superior Chippewa Indians of Michigan", "136", ("MI",)),
        ("Little River Band of Ottawa Indians, Michigan", "138", ("MI",)),
        ("Little Traverse Bay Bands of Odawa Indians, Michigan", "139", ("MI",)),
        ("Match-e-be-nash-she-wish Band of Pottawatomi Indians of Michigan", "153", ("MI",)),
        ("Nottawaseppi Huron Band of the Potawatomi, Michigan", "178", ("MI",)),
        ("Saginaw Chippewa Indian Tribe of Michigan", "249", ("MI",)),
        ("Sault Ste. Marie Tribe of Chippewa Indians, Michigan", "263", ("MI",)),
        ("Lower Sioux Indian Community in the State of Minnesota", "145", ("MN",)),
        (
            "Minnesota Chippewa Tribe, Minnesota (Six component reservations: Bois Forte Band (Nett Lake); Fond du Lac Band; Grand Portage Band; Leech Lake Band; Mille Lacs Band; White Earth Band)",
            "161", ("MN",)),
        ("Prairie Island Indian Community in the State of Minnesota", "211", ("MN",)),
        ("Red Lake Band of Chippewa Indians, Minnesota", "237", ("MN",)),
        ("Shakopee Mdewakanton Sioux Community of Minnesota", "269", ("MN",)),
        ("Upper Sioux Community, Minnesota", "316", ("MN", "WI",)),
        ("Eastern Shawnee Tribe of Oklahoma", "77", ("MO", "OK",)),
        ("Mississippi Band of Choctaw Indians", "162", ("MS", "TN",)),
        ("Assiniboine and Sioux Tribes of the Fort Peck Indian Reservation, Montana", "10", ("MT",)),
        ("Blackfeet Tribe of the Blackfeet Indian Reservation of Montana", "20", ("MT",)),
        ("Chippewa Cree Indians of the Rocky Boy's Reservation, Montana", "43", ("MT",)),
        ("Confederated Salish and Kootenai Tribes of the Flathead Reservation", "53", ("MT",)),
        ("Crow Tribe of Montana", "69", ("MT",)),
        ("Fort Belknap Indian Community of the Fort Belknap Reservation of Montana", "86", ("MT",)),
        ("Little Shell Tribe of Chippewa Indians of Montana", "597", ("MT",)),
        ("Northern Cheyenne Tribe of the Northern Cheyenne Indian Reservation, Montana", "175", ("MT",)),
        ("Turtle Mountain Band of Chippewa Indians of North Dakota", "311", ("MT", "ND", "SD",)),
        ("Eastern Band of Cherokee Indians", "76", ("NC",)),
        ("Spirit Lake Tribe, North Dakota", "286", ("ND",)),
        ("Three Affiliated Tribes of the Fort Berthold Reservation, North Dakota", "301", ("ND",)),
        ("Sisseton-Wahpeton Oyate of the Lake Traverse Reservation, South Dakota", "278", ("ND", "SD",)),
        ("Standing Rock Sioux Tribe of North & South Dakota", "289", ("ND", "SD",)),
        ("Santee Sioux Nation, Nebraska", "261", ("NE",)),
        ("Oglala Sioux Tribe", "179", ("NE", "SD",)),
        ("Jicarilla Apache Nation, New Mexico", "117", ("NM",)),
        ("Kewa Pueblo, New Mexico", "123", ("NM",)),
        ("Mescalero Apache Tribe of the Mescalero Reservation, New Mexico", "157", ("NM",)),
        ("Ohkay Owingeh, New Mexico", "180", ("NM",)),
        ("Pueblo of Acoma, New Mexico", "212", ("NM",)),
        ("Pueblo of Cochiti, New Mexico", "213", ("NM",)),
        ("Pueblo of Isleta, New Mexico", "215", ("NM",)),
        ("Pueblo of Jemez, New Mexico", "214", ("NM",)),
        ("Pueblo of Laguna, New Mexico", "216", ("NM",)),
        ("Pueblo of Nambe, New Mexico", "217", ("NM",)),
        ("Pueblo of Picuris, New Mexico", "218", ("NM",)),
        ("Pueblo of Pojoaque, New Mexico", "219", ("NM",)),
        ("Pueblo of San Felipe, New Mexico", "220", ("NM",)),
        ("Pueblo of San Ildefonso, New Mexico", "221", ("NM",)),
        ("Pueblo of Sandia, New Mexico", "222", ("NM",)),
        ("Pueblo of Santa Ana, New Mexico", "223", ("NM",)),
        ("Pueblo of Santa Clara, New Mexico", "224", ("NM",)),
        ("Pueblo of Taos, New Mexico", "225", ("NM",)),
        ("Pueblo of Tesuque, New Mexico", "226", ("NM",)),
        ("Pueblo of Zia, New Mexico", "227", ("NM",)),
        ("Santo Domingo Pueblo", "123", ("NM",)),
        ("Duckwater Shoshone Tribe of the Duckwater Reservation, Nevada", "75", ("NV",)),
        ("Ely Shoshone Tribe of Nevada", "80", ("NV",)),
        ("Las Vegas Tribe of Paiute Indians of the Las Vegas Indian Colony, Nevada", "137", ("NV",)),
        ("Lovelock Paiute Tribe of the Lovelock Indian Colony, Nevada", "142", ("NV",)),
        ("Moapa Band of Paiute Indians of the Moapa River Indian Reservation, Nevada", "163", ("NV",)),
        ("Paiute-Shoshone Tribe of the Fallon Reservation and Colony, Nevada", "190", ("NV",)),
        ("Pyramid Lake Paiute Tribe of the Pyramid Lake Reservation, Nevada", "229", ("NV",)),
        ("Reno-Sparks Indian Colony, Nevada", "240", ("NV",)),
        ("Summit Lake Paiute Tribe of Nevada", "292", ("NV",)),
        (
            "Te-Moak Tribe of Western Shoshone Indians of Nevada (Four constituent bands: Battle Mountain Band; Elko Band; South Fork Band and Wells Band)",
            "299", ("NV",)),
        ("Walker River Paiute Tribe of the Walker River Reservation, Nevada", "321", ("NV",)),
        ("Winnemucca Indian Colony of Nevada", "328", ("NV",)),
        ("Yerington Paiute Tribe of the Yerington Colony & Campbell Ranch, Nevada", "334", ("NV",)),
        ("Yomba Shoshone Tribe of the Yomba Reservation, Nevada", "336", ("NV",)),
        ("Fort McDermitt Paiute and Shoshone Tribes of the Fort McDermitt Indian Reservation, Nevada and Oregon", "89",
         ("NV", "OR",)),
        ("Confederated Tribes of the Goshute Reservation, Nevada and Utah", "57", ("NV", "UT",)),
        ("Cayuga Nation", "34", ("NY",)),
        ("Oneida Indian Nation", "182", ("NY",)),
        ("Onondaga Nation", "184", ("NY",)),
        ("Saint Regis Mohawk Tribe", "251", ("NY",)),
        ("Seneca Nation of Indians", "267", ("NY",)),
        ("Shinnecock Indian Nation", "273", ("NY",)),
        ("Tonawanda Band of Seneca", "303", ("NY",)),
        ("Tuscarora Nation", "312", ("NY",)),
        ("Absentee-Shawnee Tribe of Indians of Oklahoma", "1", ("OK",)),
        ("Alabama-Quassarte Tribal Town", "5", ("OK",)),
        ("Apache Tribe of Oklahoma", "7", ("OK",)),
        ("Caddo Nation of Oklahoma", "27", ("OK",)),
        ("Cherokee Nation", "38", ("OK",)),
        ("Cheyenne and Arapaho Tribes, Oklahoma", "39", ("OK",)),
        ("Citizen Potawatomi Nation, Oklahoma", "46", ("OK",)),
        ("Comanche Nation, Oklahoma", "52", ("OK",)),
        ("Delaware Nation, Oklahoma", "72", ("OK",)),
        ("Delaware Tribe of Indians", "73", ("OK",)),
        ("Iowa Tribe of Oklahoma", "112", ("OK",)),
        ("Kaw Nation, Oklahoma", "122", ("OK",)),
        ("Kialegee Tribal Town", "125", ("OK",)),
        ("Kickapoo Tribe of Oklahoma", "127", ("OK",)),
        ("Kiowa Indian Tribe of Oklahoma", "129", ("OK",)),
        ("Miami Tribe of Oklahoma", "158", ("OK",)),
        ("Modoc Nation", "164", ("OK",)),
        ("Otoe-Missouria Tribe of Indians, Oklahoma", "187", ("OK",)),
        ("Ottawa Tribe of Oklahoma", "186", ("OK",)),
        ("Pawnee Nation of Oklahoma", "197", ("OK",)),
        ("Peoria Tribe of Indians of Oklahoma", "200", ("OK",)),
        ("Ponca Tribe of Indians of Oklahoma", "206", ("OK",)),
        ("Sac & Fox Nation, Oklahoma", "248", ("OK",)),
        ("Seneca-Cayuga Nation", "268", ("OK",)),
        ("Shawnee Tribe", "270", ("OK",)),
        ("The Chickasaw Nation", "41", ("OK",)),
        ("The Choctaw Nation of Oklahoma", "45", ("OK",)),
        ("The Osage Nation", "185", ("OK",)),
        ("The Seminole Nation of Oklahoma", "265", ("OK",)),
        ("Thlopthlocco Tribal Town", "300", ("OK",)),
        ("Tonkawa Tribe of Indians of Oklahoma", "304", ("OK",)),
        ("United Keetoowah Band of Cherokee Indians in Oklahoma", "315", ("OK",)),
        ("Wichita and Affiliated Tribes (Wichita, Keechi, Waco & Tawakonie), Oklahoma", "325", ("OK",)),
        ("Burns Paiute Tribe", "24", ("OR",)),
        ("Confederated Tribes of Siletz Indians of Oregon", "59", ("OR",)),
        ("Confederated Tribes of the Coos, Lower Umpqua and Siuslaw Indians", "56", ("OR",)),
        ("Confederated Tribes of the Grand Ronde Community of Oregon", "58", ("OR",)),
        ("Confederated Tribes of the Umatilla Indian Reservation", "60", ("OR",)),
        ("Confederated Tribes of the Warm Springs Reservation of Oregon", "61", ("OR",)),
        ("Coquille Indian Tribe", "63", ("OR",)),
        ("Cow Creek Band of Umpqua Tribe of Indians", "66", ("OR",)),
        ("Klamath Tribes", "130", ("OR",)),
        ("Narragansett Indian Tribe", "170", ("RI",)),
        ("Catawba Indian Nation (aka Catawba Tribe of South Carolina)", "33", ("SC",)),
        ("Cheyenne River Sioux Tribe of the Cheyenne River Reservation, South Dakota", "40", ("SD",)),
        ("Crow Creek Sioux Tribe of the Crow Creek Reservation, South Dakota", "70", ("SD",)),
        ("Flandreau Santee Sioux Tribe of South Dakota", "84", ("SD",)),
        ("Lower Brule Sioux Tribe of the Lower Brule Reservation, South Dakota", "143", ("SD",)),
        ("Rosebud Sioux Tribe of the Rosebud Indian Reservation, South Dakota", "244", ("SD",)),
        ("Yankton Sioux Tribe of South Dakota", "331", ("SD",)),
        ("Alabama-Coushatta Tribe of Texas", "4", ("TX",)),
        ("Kickapoo Traditional Tribe of Texas", "128", ("TX",)),
        ("Ysleta del Sur Pueblo", "337", ("TX",)),
        ("Northwestern Band of the Shoshone Nation", "177", ("UT",)),
        (
            "Paiute Indian Tribe of Utah (Cedar Band of Paiutes, Kanosh Band of Paiutes, Koosharem Band of Paiutes, Indian Peaks Band of Paiutes, and Shivwits Band of Paiutes)",
            "188", ("UT",)),
        ("Skull Valley Band of Goshute Indians of Utah", "280", ("UT",)),
        ("Ute Indian Tribe of the Uintah & Ouray Reservation, Utah", "318", ("UT",)),
        ("Chickahominy Indian Tribe", "591", ("VA",)),
        ("Chickahominy Indian Tribe--Eastern Division", "592", ("VA",)),
        ("Monacan Indian Nation", "593", ("VA",)),
        ("Nansemond Indian Nation", "594", ("VA",)),
        ("Pamunkey Indian Tribe", "590", ("VA",)),
        ("Rappahannock Tribe, Inc.", "595", ("VA",)),
        ("Upper Mattaponi Tribe", "596", ("VA",)),
        ("Confederated Tribes and Bands of the Yakama Nation", "62", ("WA",)),
        ("Confederated Tribes of the Chehalis Reservation", "54", ("WA",)),
        ("Confederated Tribes of the Colville Reservation", "55", ("WA",)),
        ("Cowlitz Indian Tribe", "67", ("WA",)),
        ("Hoh Indian Tribe", "102", ("WA",)),
        ("Jamestown S'Klallam Tribe", "114", ("WA",)),
        ("Kalispel Indian Community of the Kalispel Reservation", "119", ("WA",)),
        ("Lower Elwha Tribal Community", "144", ("WA",)),
        ("Lummi Tribe of the Lummi Reservation", "146", ("WA",)),
        ("Makah Indian Tribe of the Makah Indian Reservation", "148", ("WA",)),
        ("Muckleshoot Indian Tribe", "168", ("WA",)),
        ("Nisqually Indian Tribe", "173", ("WA",)),
        ("Nooksack Indian Tribe", "174", ("WA",)),
        ("Port Gamble S'Klallam Tribe", "208", ("WA",)),
        ("Puyallup Tribe of the Puyallup Reservation", "228", ("WA",)),
        ("Quileute Tribe of the Quileute Reservation", "233", ("WA",)),
        ("Quinault Indian Nation", "234", ("WA",)),
        ("Samish Indian Nation", "253", ("WA",)),
        ("Sauk-Suiattle Indian Tribe", "262", ("WA",)),
        ("Shoalwater Bay Indian Tribe of the Shoalwater Bay Indian Reservation", "274", ("WA",)),
        ("Skokomish Indian Tribe", "279", ("WA",)),
        ("Snoqualmie Indian Tribe", "282", ("WA",)),
        ("Spokane Tribe of the Spokane Reservation", "287", ("WA",)),
        ("Squaxin Island Tribe of the Squaxin Island Reservation", "288", ("WA",)),
        ("Stillaguamish Tribe of Indians of Washington", "291", ("WA",)),
        ("Suquamish Indian Tribe of the Port Madison Reservation", "293", ("WA",)),
        ("Swinomish Indian Tribal Community", "295", ("WA",)),
        ("Tulalip Tribes of Washington", "308", ("WA",)),
        ("Upper Skagit Indian Tribe", "317", ("WA",)),
        ("Bad River Band of the Lake Superior Tribe of Chippewa Indians of the Bad River Reservation, Wisconsin", "12",
         ("WI",)),
        ("Forest County Potawatomi Community, Wisconsin", "85", ("WI",)),
        ("Ho-Chunk Nation of Wisconsin", "101", ("WI",)),
        ("Lac Courte Oreilles Band of Lake Superior Chippewa Indians of Wisconsin", "134", ("WI",)),
        (
            "Lac du Flambeau Band of Lake Superior Chippewa Indians of the Lac du Flambeau Reservation of Wisconsin",
            "135",
            ("WI",)),
        ("Menominee Indian Tribe of Wisconsin", "155", ("WI",)),
        ("Oneida Nation", "183", ("WI",)),
        ("Red Cliff Band of Lake Superior Chippewa Indians of Wisconsin", "236", ("WI",)),
        ("Sokaogon Chippewa Community, Wisconsin", "284", ("WI",)),
        ("St. Croix Chippewa Indians of Wisconsin", "250", ("WI",)),
        ("Stockbridge Munsee Community, Wisconsin", "290", ("WI",)),
        ("Arapaho Tribe of the Wind River Reservation, Wyoming", "8", ("WY",)),
        ("Eastern Shoshone Tribe of the Wind River Reservation, Wyoming", "275", ("WY",))]
    for tribe, epa_code, states in data:
        tribe, _ = TribeTable.get_or_create(tribe=tribe, epa_code=epa_code)
        for code in states:
            state = StateTable.get(StateTable.code == code)
            TribeStateTable.get_or_create(tribe=tribe, state=state)


def bootstrap_fips_codes():
    data = [
        ("Alabama", "01"),
        ("Alaska", "02"),
        ("Arizona", "04"),
        ("Arkansas", "05"),
        ("California", "06"),
        ("Colorado", "08"),
        ("Connecticut", "09"),
        ("Delaware", "10"),
        ("District of Columbia", "11"),
        ("Florida", "12"),
        ("Georgia", "13"),
        ("Hawaii", "15"),
        ("Idaho", "16"),
        ("Illinois", "17"),
        ("Indiana", "18"),
        ("Iowa", "19"),
        ("Kansas", "20"),
        ("Kentucky", "21"),
        ("Louisiana", "22"),
        ("Maine", "23"),
        ("Maryland", "24"),
        ("Massachusetts", "25"),
        ("Michigan", "26"),
        ("Minnesota", "27"),
        ("Mississippi", "28"),
        ("Missouri", "29"),
        ("Montana", "30"),
        ("Nebraska", "31"),
        ("Nevada", "32"),
        ("New Hampshire", "33"),
        ("New Jersey", "34"),
        ("New Mexico", "35"),
        ("New York", "36"),
        ("North Carolina", "37"),
        ("North Dakota", "38"),
        ("Ohio", "39"),
        ("Oklahoma", "40"),
        ("Oregon", "41"),
        ("Pennsylvania", "42"),
        ("Rhode Island", "44"),
        ("South Carolina", "45"),
        ("South Dakota", "46"),
        ("Tennessee", "47"),
        ("Texas", "48"),
        ("Utah", "49"),
        ("Vermont", "50"),
        ("Virginia", "51"),
        ("Washington", "53"),
        ("West Virginia", "54"),
        ("Wisconsin", "55"),
        ("Wyoming", "56"),
        ("U.S. Virgin Islands", "78"),
        ("Guam", "66"),
        ("Northern Mariana Islands", "69"),
        ("American Samoa", "60"),
        ("Puerto Rico", "72")
    ]
    for state, fips_code in data:
        StateTable.update(fips_code=fips_code).where(StateTable.name == state).execute()
