from dataclasses import dataclass, field

from peewee import IntegerField, TextField


@dataclass(kw_only=True)
class Context:
    id: int | None = field(default=None)
    e1: int | IntegerField | None = field(default=None)
    e2: int | IntegerField | None = field(default=None)


@dataclass(kw_only=True)
class Child:
    id: int | None = field(default=None)
    first_name: str | TextField | None = field(default=None)
    last_name: str | TextField | None = field(default=None)
    e4: str | TextField | None = field(default=None)
    e5: int | IntegerField | None = field(default=None)
    e6: int | IntegerField | None = field(default=None)
    e13: int | IntegerField | None = field(default=None)
    e14: int | IntegerField | None = field(default=None)
    e15: int | IntegerField | None = field(default=None)
    e16: int | IntegerField | None = field(default=None)
    e17: int | IntegerField | None = field(default=None)
    e18: int | IntegerField | None = field(default=None)
    e19: int | IntegerField | None = field(default=None)
    e20: int | IntegerField | None = field(default=None)
    e21: int | IntegerField | None = field(default=None)


@dataclass(kw_only=True)
class RecognizedTribe:
    id: int | None = field(default=None)
    ooh: int | None = field(default=None)
    e9: int | IntegerField | None = field(default=None)


@dataclass(kw_only=True)
class SecondParent:
    id: int | None = field(default=None)
    ooh: int | None = field(default=None)
    e64: int | IntegerField | None = field(default=None)
    e66: int | IntegerField | None = field(default=None)
    e68: int | IntegerField | None = field(default=None)


@dataclass(kw_only=True)
class PermanencyPlan:
    id: int | None = field(default=None)
    removal: int | None = field(default=None)
    e147: int | IntegerField | None = field(default=None)
    e148: int | IntegerField | None = field(default=None)


@dataclass(kw_only=True)
class PeriodicReview:
    id: int | None = field(default=None)
    removal: int | None = field(default=None)
    e149: int | IntegerField | None = field(default=None)


@dataclass(kw_only=True)
class PermanencyHearing:
    id: int | None = field(default=None)
    removal: int | None = field(default=None)
    e150: int | IntegerField | None = field(default=None)


@dataclass(kw_only=True)
class CaseVisit:
    id: int | None = field(default=None)
    removal: int | None = field(default=None)
    e151: int | IntegerField | None = field(default=None)
    e152: int | IntegerField | None = field(default=None)


@dataclass(kw_only=True)
class LivingArrangement:
    id: int | None = field(default=None)
    removal: int | None = field(default=None)
    e40: int | IntegerField | None = field(default=None)
    e58: int | IntegerField | None = field(default=None)
    e112: int | IntegerField | None = field(default=None)
    e113: int | IntegerField | None = field(default=None)
    e114: int | IntegerField | None = field(default=None)
    e115: int | IntegerField | None = field(default=None)
    e116: int | IntegerField | None = field(default=None)
    e117: int | IntegerField | None = field(default=None)
    e118: int | IntegerField | None = field(default=None)
    e119: int | IntegerField | None = field(default=None)
    e120: int | IntegerField | None = field(default=None)
    e121: int | IntegerField | None = field(default=None)
    e122: int | IntegerField | None = field(default=None)
    e123: int | IntegerField | None = field(default=None)
    e124: int | IntegerField | None = field(default=None)
    e125: int | IntegerField | None = field(default=None)
    e126: int | IntegerField | None = field(default=None)
    e127: int | IntegerField | None = field(default=None)
    e128: int | IntegerField | None = field(default=None)
    e129: int | IntegerField | None = field(default=None)
    e130: int | IntegerField | None = field(default=None)
    e131: int | IntegerField | None = field(default=None)
    e132: int | IntegerField | None = field(default=None)
    e133: int | IntegerField | None = field(default=None)
    e134: int | IntegerField | None = field(default=None)
    e135: int | IntegerField | None = field(default=None)
    e136: int | IntegerField | None = field(default=None)
    e137: int | IntegerField | None = field(default=None)
    e138: int | IntegerField | None = field(default=None)
    e139: int | IntegerField | None = field(default=None)
    e140: int | IntegerField | None = field(default=None)
    e141: int | IntegerField | None = field(default=None)
    e142: int | IntegerField | None = field(default=None)
    e143: int | IntegerField | None = field(default=None)
    e144: int | IntegerField | None = field(default=None)
    e145: int | IntegerField | None = field(default=None)
    e146: int | IntegerField | None = field(default=None)


@dataclass(kw_only=True)
class Removal1993:
    id: int | None = field(default=None)
    ooh: int | None = field(default=None)
    e69: int | IntegerField | None = field(default=None)
    e153: int | IntegerField | None = field(default=None)
    e155: int | IntegerField | None = field(default=None)


@dataclass(kw_only=True)
class Removal2020:
    id: int | None = field(default=None)
    ooh: int | None = field(default=None)
    e3: int | IntegerField | None = field(default=None)
    e69: int | IntegerField | None = field(default=None)
    e70: int | IntegerField | None = field(default=None)
    e71: int | IntegerField | None = field(default=None)
    e72: int | IntegerField | None = field(default=None)
    e73: int | IntegerField | None = field(default=None)
    e74: int | IntegerField | None = field(default=None)
    e75: int | IntegerField | None = field(default=None)
    e76: int | IntegerField | None = field(default=None)
    e77: int | IntegerField | None = field(default=None)
    e78: int | IntegerField | None = field(default=None)
    e79: int | IntegerField | None = field(default=None)
    e80: int | IntegerField | None = field(default=None)
    e81: int | IntegerField | None = field(default=None)
    e82: int | IntegerField | None = field(default=None)
    e83: int | IntegerField | None = field(default=None)
    e84: int | IntegerField | None = field(default=None)
    e85: int | IntegerField | None = field(default=None)
    e86: int | IntegerField | None = field(default=None)
    e87: int | IntegerField | None = field(default=None)
    e88: int | IntegerField | None = field(default=None)
    e89: int | IntegerField | None = field(default=None)
    e90: int | IntegerField | None = field(default=None)
    e91: int | IntegerField | None = field(default=None)
    e92: int | IntegerField | None = field(default=None)
    e93: int | IntegerField | None = field(default=None)
    e94: int | IntegerField | None = field(default=None)
    e95: int | IntegerField | None = field(default=None)
    e96: int | IntegerField | None = field(default=None)
    e97: int | IntegerField | None = field(default=None)
    e98: int | IntegerField | None = field(default=None)
    e99: int | IntegerField | None = field(default=None)
    e100: int | IntegerField | None = field(default=None)
    e101: int | IntegerField | None = field(default=None)
    e102: int | IntegerField | None = field(default=None)
    e103: int | IntegerField | None = field(default=None)
    e104: int | IntegerField | None = field(default=None)
    e105: int | IntegerField | None = field(default=None)
    living_arrangements: list[LivingArrangement] = field(default_factory=list)
    permanency_plans: list[PermanencyPlan] = field(default_factory=list)
    periodic_reviews: list[PeriodicReview] = field(default_factory=list)
    permanency_hearings: list[PermanencyHearing] = field(default_factory=list)
    case_worker_visits: list[CaseVisit] = field(default_factory=list)
    e153: int | IntegerField | None = field(default=None)
    e154: int | IntegerField | None = field(default=None)
    e155: int | IntegerField | None = field(default=None)
    e156: int | IntegerField | None = field(default=None)
    e157: int | IntegerField | None = field(default=None)
    e158: int | IntegerField | None = field(default=None)
    e159: int | IntegerField | None = field(default=None)
    e160: int | IntegerField | None = field(default=None)
    e161: int | IntegerField | None = field(default=None)
    e162: int | IntegerField | None = field(default=None)
    e163: int | IntegerField | None = field(default=None)
    e164: int | IntegerField | None = field(default=None)
    e165: int | IntegerField | None = field(default=None)
    e166: int | IntegerField | None = field(default=None)
    e167: int | IntegerField | None = field(default=None)
    e168: int | IntegerField | None = field(default=None)
    e169: int | IntegerField | None = field(default=None)
    e170: int | IntegerField | None = field(default=None)
    e171: int | IntegerField | None = field(default=None)
    e172: int | IntegerField | None = field(default=None)
    e173: int | IntegerField | None = field(default=None)
    e174: int | IntegerField | None = field(default=None)
    e175: int | IntegerField | None = field(default=None)
    e176: int | IntegerField | None = field(default=None)
    e177: int | IntegerField | None = field(default=None)
    e178: int | IntegerField | None = field(default=None)
    e179: int | IntegerField | None = field(default=None)
    e180: int | IntegerField | None = field(default=None)
    e181: int | IntegerField | None = field(default=None)
    e182: int | IntegerField | None = field(default=None)
    e183: int | IntegerField | None = field(default=None)
    e184: int | IntegerField | None = field(default=None)
    e185: int | IntegerField | None = field(default=None)
    e186: int | IntegerField | None = field(default=None)


@dataclass(kw_only=True)
class OOHRecord:
    id: int | None = field(default=None)
    child: Child
    context: Context
    funding: int | IntegerField | None = field(default=None)
    e7: int | IntegerField | None = field(default=None)
    e8: int | IntegerField | None = field(default=None)
    e10: int | IntegerField | None = field(default=None)
    e11: int | IntegerField | None = field(default=None)
    e12: int | IntegerField | None = field(default=None)
    e22: int | IntegerField | None = field(default=None)
    e23: int | IntegerField | None = field(default=None)
    e24: int | IntegerField | None = field(default=None)
    e25: int | IntegerField | None = field(default=None)
    e26: int | IntegerField | None = field(default=None)
    e27: int | IntegerField | None = field(default=None)
    e28: int | IntegerField | None = field(default=None)
    e29: int | IntegerField | None = field(default=None)
    e30: int | IntegerField | None = field(default=None)
    e31: int | IntegerField | None = field(default=None)
    e32: int | IntegerField | None = field(default=None)
    e33: int | IntegerField | None = field(default=None)
    e34: int | IntegerField | None = field(default=None)
    e35: int | IntegerField | None = field(default=None)
    e36: int | IntegerField | None = field(default=None)
    e37: int | IntegerField | None = field(default=None)
    e38: int | IntegerField | None = field(default=None)
    e39: int | IntegerField | None = field(default=None)
    # e40: int | IntegerField | None = field(default=None)
    e41: int | IntegerField | None = field(default=None)
    e42: int | IntegerField | None = field(default=None)
    e43: int | IntegerField | None = field(default=None)
    e44: int | IntegerField | None = field(default=None)
    e45: int | IntegerField | None = field(default=None)
    e46: int | IntegerField | None = field(default=None)
    e47: int | IntegerField | None = field(default=None)
    e48: int | IntegerField | None = field(default=None)
    e49: int | IntegerField | None = field(default=None)
    e50: int | IntegerField | None = field(default=None)
    e51: int | IntegerField | None = field(default=None)
    e52: int | IntegerField | None = field(default=None)
    e53: int | IntegerField | None = field(default=None)
    e54: int | IntegerField | None = field(default=None)
    e55: int | IntegerField | None = field(default=None)
    e56: int | IntegerField | None = field(default=None)
    e57: int | IntegerField | None = field(default=None)
    # e58: int | IntegerField | None = field(default=None)
    e59: int | IntegerField | None = field(default=None)
    e60: int | IntegerField | None = field(default=None)
    e61: int | IntegerField | None = field(default=None)
    e62: int | IntegerField | None = field(default=None)
    e63: int | IntegerField | None = field(default=None)
    e65: int | IntegerField | None = field(default=None)
    e67: int | IntegerField | None = field(default=None)
    e106: int | IntegerField | None = field(default=None)
    e107: int | IntegerField | None = field(default=None)
    e108: int | IntegerField | None = field(default=None)
    e109: int | IntegerField | None = field(default=None)
    e110: int | IntegerField | None = field(default=None)
    e111: int | IntegerField | None = field(default=None)
    tribes: list[RecognizedTribe] = field(default_factory=list)
    second_parents: list[SecondParent] = field(default_factory=list)
    removals1993: list[Removal1993] = field(default_factory=list)
    removals2020: list[Removal2020] = field(default_factory=list)


@dataclass(kw_only=True)
class ARecord:
    id: int | None = field(default=None)
    child: Child
    context: Context
    a5: int | IntegerField | None = field(default=None)
    a6: int | IntegerField | None = field(default=None)
    a7: int | IntegerField | None = field(default=None)
    a8: int | IntegerField | None = field(default=None)
    a9: int | IntegerField | None = field(default=None)
    a10: int | IntegerField | None = field(default=None)
    a11: int | IntegerField | None = field(default=None)
    a12: int | IntegerField | None = field(default=None)
    a13: int | IntegerField | None = field(default=None)
    a14: int | IntegerField | None = field(default=None)
    a15: int | IntegerField | None = field(default=None)
    a16: int | IntegerField | None = field(default=None)
    a17: int | IntegerField | None = field(default=None)
    a18: int | IntegerField | None = field(default=None)
    a19: int | IntegerField | None = field(default=None)


@dataclass(kw_only=True)
class Tribe:
    id: int
    tribe: str | TextField
    epa_code: int | TextField
    states: list[str] | None

@dataclass(kw_only=True)
class State:
    id: int
    state: str | TextField
    name: str | TextField
    fips_code: int | IntegerField
    tribes: list[str] | None

