from controllers.child_controller import ChildController
from controllers.export_controller import ExportController
from dialogs.main_window2_dialog import MainWindow2Dialog
from model import ConfigTable
from model.models import FileType, ReportType

FIPS_CODES = {"Alabama": "01", "Alaska": "02", "Arizona": "04", "Arkansas": "05", "California": "06",
              "Colorado": "08", "Connecticut": "09", "Delaware": "10", "District of Columbia": "11",
              "Florida": "12", "Georgia": "13", "Hawaii": "15", "Idaho": "16", "Illinois": "17", "Indiana": "18",
              "Iowa": "19", "Kansas": "20", "Kentucky": "21", "Louisiana": "22", "Maine": "23", "Maryland": "24",
              "Massachusetts": "25", "Michigan": "26", "Minnesota": "27", "Mississippi": "28", "Missouri": "29",
              "Montana": "30", "Nebraska": "31", "Nevada": "32", "New Hampshire": "33", "New Jersey": "34",
              "New Mexico": "35", "New York": "36", "North Carolina": "37", "North Dakota": "38", "Ohio": "39",
              "Oklahoma": "40", "Oregon": "41", "Pennsylvania": "42", "Rhode Island": "44", "South Carolina": "45",
              "South Dakota": "46", "Tennessee": "47", "Texas": "48", "Utah": "49", "Vermont": "50",
              "Virginia": "51", "Washington": "53", "West Virginia": "54", "Wisconsin": "55", "Wyoming": "56",
              "Virgin Islands of the U.S.": "78"
              }
EPA_CODES = {
    "Agdaagux Tribe of King Cove (AK)": "341",
    "Akiachak Native Community (AK)": "343",
    "Akiak Native Community (AK)": "344",
    "Alatna Village (AK)": "347",
    "Algaaciq Native Village (St. Mary's) (AK)": "349",
    "Allakaket Village (AK)": "350",
    "Alutiiq Tribe of Old Harbor (AK)": "495",
    "Angoon Community Association (AK)": "354",
    "Anvik Village (AK)": "356",
    "Arctic Village (See Native Village of Venetie Tribal Government) (AK)": "357",
    "Asa'carsarmiut Tribe (AK)": "358",
    "Atqasuk Village (Atkasook) (AK)": "361",
    "Beaver Village (AK)": "363",
    "Birch Creek Tribe (AK)": "366",
    "Central Council of the Tlingit & Haida Indian Tribes (AK)": "551",
    "Chalkyitsik Village (AK)": "371",
    "Cheesh-Na Tribe (AK)": "372",
    "Chevak Native Village (AK)": "374",
    "Chickaloon Native Village (AK)": "375",
    "Chignik Bay Tribal Council (AK)": "376",
    "Chignik Lake Village (AK)": "378",
    "Chilkat Indian Village (Klukwan) (AK)": "379",
    "Chilkoot Indian Association (Haines) (AK)": "380",
    "Chinik Eskimo Community (Golovin) (AK)": "381",
    "Chuloonawick Native Village (AK)": "384",
    "Circle Native Community (AK)": "385",
    "Craig Tribal Association (AK)": "388",
    "Curyung Tribal Council (AK)": "390",
    "Douglas Indian Association (AK)": "394",
    "Egegik Village (AK)": "397",
    "Eklutna Native Village (AK)": "398",
    "Emmonak Village (AK)": "402",
    "Evansville Village (aka Bettles Field) (AK)": "403",
    "Galena Village (aka Louden Village) (AK)": "408",
    "Gulkana Village Council (AK)": "413",
    "Healy Lake Village (AK)": "415",
    "Holy Cross Tribe (AK)": "416",
    "Hoonah Indian Association (AK)": "417",
    "Hughes Village (AK)": "419",
    "Huslia Village (AK)": "420",
    "Hydaburg Cooperative Association (AK)": "421",
    "Igiugig Village (AK)": "422",
    "Inupiat Community of the Arctic Slope (AK)": "424",
    "Iqugmiut Traditional Council (AK)": "425",
    "Ivanof Bay Tribe (AK)": "426",
    "Kaguyak Village (AK)": "427",
    "Kaktovik Village (aka Barter Island) (AK)": "429",
    "Kasigluk Traditional Elders Council (AK)": "435",
    "Kenaitze Indian Tribe (AK)": "436",
    "Ketchikan Indian Corporation (AK)": "437",
    "King Island Native Community (AK)": "439",
    "King Salmon Tribe (AK)": "440",
    "Klawock Cooperative Association (AK)": "443",
    "Knik Tribe (AK)": "445",
    "Kokhanok Village (AK)": "447",
    "Koyukuk Native Village (AK)": "452",
    "Levelock Village (AK)": "457",
    "Lime Village (AK)": "458",
    "Manley Hot Springs Village (AK)": "460",
    "Manokotak Village (AK)": "461",
    "McGrath Native Village (AK)": "464",
    "Mentasta Traditional Council (AK)": "466",
    "Metlakatla Indian Community, Annette Island Reserve (AK)": "467",
    "Naknek Native Village (AK)": "469",
    "Native Village of Afognak (AK)": "340",
    "Native Village of Akhiok (AK)": "342",
    "Native Village of Akutan (AK)": "345",
    "Native Village of Aleknagik (AK)": "348",
    "Native Village of Ambler (AK)": "351",
    "Native Village of Atka (AK)": "359",
    "Native Village of Atqasuk (AK)": "361",
    "Native Village of Barrow Inupiat Traditional Government (AK)": "362",
    "Native Village of Belkofski (AK)": "364",
    "Native Village of Brevig Mission (AK)": "367",
    "Native Village of Buckland (AK)": "368",
    "Native Village of Cantwell (AK)": "369",
    "Native Village of Chenega (aka Chanega) (AK)": "370",
    "Native Village of Chignik Lagoon (AK)": "377",
    "Native Village of Chitina (AK)": "382",
    "Native Village of Chuathbaluk (Russian Mission, Kuskokwim) (AK)": "383",
    "Native Village of Council (AK)": "387",
    "Native Village of Deering (AK)": "391",
    "Native Village of Diomede (aka Inalik) (AK)": "392",
    "Native Village of Eagle (AK)": "395",
    "Native Village of Eek (AK)": "396",
    "Native Village of Ekuk (AK)": "399",
    "Native Village of Ekwok (AK)": "400",
    "Native Village of Elim (AK)": "401",
    "Native Village of Eyak (Cordova) (AK)": "404",
    "Native Village of False Pass (AK)": "405",
    "Native Village of Fort Yukon (AK)": "406",
    "Native Village of Gakona (AK)": "407",
    "Native Village of Gambell (AK)": "409",
    "Native Village of Georgetown (AK)": "410",
    "Native Village of Goodnews Bay (AK)": "411",
    "Native Village of Hamilton (AK)": "414",
    "Native Village of Hooper Bay (AK)": "418",
    "Native Village of Kanatak (AK)": "432",
    "Native Village of Karluk (AK)": "433",
    "Native Village of Kiana (AK)": "438",
    "Native Village of Kipnuk (AK)": "441",
    "Native Village of Kivalina (AK)": "442",
    "Native Village of Kluti Kaah (aka Copper Center) (AK)": "444",
    "Native Village of Kobuk (AK)": "446",
    "Native Village of Kongiganak (AK)": "448",
    "Native Village of Kotzebue (AK)": "450",
    "Native Village of Koyuk (AK)": "451",
    "Native Village of Kwigillingok (AK)": "454",
    "Native Village of Kwinhagak (aka Quinhagak) (AK)": "455",
    "Native Village of Larsen Bay (AK)": "456",
    "Native Village of Marshall (aka Fortuna Ledge) (AK)": "462",
    "Native Village of Mary's Igloo (AK)": "463",
    "Native Village of Mekoryuk (AK)": "465",
    "Native Village of Minto (AK)": "468",
    "Native Village of Nanwalek (aka English Bay) (AK)": "470",
    "Native Village of Napaimute (AK)": "471",
    "Native Village of Napakiak (AK)": "472",
    "Native Village of Napaskiak (AK)": "473",
    "Native Village of Nelson Lagoon (AK)": "474",
    "Native Village of Nightmute (AK)": "480",
    "Native Village of Nikolski (AK)": "482",
    "Native Village of Noatak (AK)": "484",
    "Native Village of Nuiqsut (aka Nooiksut) (AK)": "489",
    "Native Village of Nunam Iqua (AK)": "492",
    "Native Village of Nunapitchuk (AK)": "493",
    "Native Village of Ouzinkie (AK)": "498",
    "Native Village of Paimiut (AK)": "499",
    "Native Village of Perryville (AK)": "502",
    "Native Village of Pilot Point (AK)": "504",
    "Native Village of Point Hope (AK)": "508",
    "Native Village of Point Lay (AK)": "509",
    "Native Village of Port Graham (AK)": "510",
    "Native Village of Port Heiden (AK)": "511",
    "Native Village of Port Lions (AK)": "512",
    "Native Village of Ruby (AK)": "519",
    "Native Village of Saint Michael (AK)": "521",
    "Native Village of Savoonga (AK)": "524",
    "Native Village of Scammon Bay (AK)": "526",
    "Native Village of Selawik (AK)": "527",
    "Native Village of Shaktoolik (AK)": "530",
    "Native Village of Shishmaref (AK)": "531",
    "Native Village of Shungnak (AK)": "532",
    "Native Village of Stevens (AK)": "539",
    "Native Village of Tanacross (AK)": "543",
    "Native Village of Tanana (AK)": "544",
    "Native Village of Tatitlek (AK)": "546",
    "Native Village of Tazlina (AK)": "547",
    "Native Village of Teller (AK)": "549",
    "Native Village of Tetlin (AK)": "550",
    "Native Village of Tuntutuliak (AK)": "554",
    "Native Village of Tununak (AK)": "555",
    "Native Village of Tyonek (AK)": "557",
    "Native Village of Unalakleet (AK)": "560",
    "Native Village of Unga (AK)": "561",
    "Native Village of Venetie Tribal Government (Arctic Village and Village of Venetie) (AK)": "563",
    "Native Village of Wales (AK)": "565",
    "Native Village of White Mountain (AK)": "566",
    "Nenana Native Association (AK)": "475",
    "New Koliganek Village Council (AK)": "476",
    "New Stuyahok Village (AK)": "477",
    "Newhalen Village (AK)": "478",
    "Newtok Village (AK)": "479",
    "Nikolai Village (AK)": "481",
    "Ninilchik Village (AK)": "483",
    "Nome Eskimo Community (AK)": "485",
    "Nondalton Village (AK)": "486",
    "Noorvik Native Community (AK)": "487",
    "Northway Village (AK)": "488",
    "Nulato Village (AK)": "490",
    "Nunakauyarmiut Tribe (AK)": "491",
    "Organized Village of Grayling (aka Holikachuk) (AK)": "412",
    "Organized Village of Kake (AK)": "428",
    "Organized Village of Kasaan (AK)": "434",
    "Organized Village of Kwethluk (AK)": "453",
    "Organized Village of Saxman (AK)": "525",
    "Orutsararmiut Traditional Native Council (AK)": "496",
    "Oscarville Traditional Village (AK)": "497",
    "Pauloff Harbor Village (AK)": "500",
    "Pedro Bay Village (AK)": "501",
    "Petersburg Indian Association (AK)": "503",
    "Pilot Station Traditional Village (AK)": "505",
    "Pitka's Point Traditional Council (AK)": "506",
    "Platinum Traditional Village (AK)": "507",
    "Portage Creek Village (aka Ohgsenakale) (AK)": "513",
    "Pribilof Islands Aleut Communities of St. Paul & St. George Islands (AK)": "514",
    "Qagan Tayagungin Tribe of Sand Point (AK)": "515",
    "Qawalangin Tribe of Unalaska (AK)": "516",
    "Rampart Village (AK)": "517",
    "Saint George Island (See Pribilof Islands Aleut Communities of St. Paul & St. George Islands) (AK)": "520",
    "Saint Paul Island (See Pribilof Islands Aleut Communities of St. Paul & St. George Islands) (AK)": "522",
    "Salamatof Tribe (AK)": "523",
    "Seldovia Village Tribe (AK)": "528",
    "Shageluk Native Village (AK)": "529",
    "Sitka Tribe of Alaska (AK)": "533",
    "Skagway Village (AK)": "534",
    "South Naknek Village (AK)": "537",
    "Stebbins Community Association (AK)": "538",
    "Sun'aq Tribe of Kodiak (AK)": "541",
    "Takotna Village (AK)": "542",
    "Tangirnaq Native Village (AK)": "545",
    "Telida Village (AK)": "548",
    "Traditional Village of Togiak (AK)": "552",
    "Tuluksak Native Community (AK)": "553",
    "Twin Hills Village (AK)": "556",
    "Ugashik Village (AK)": "558",
    "Umkumiut Native Village (AK)": "559",
    "Village of Alakanuk (AK)": "346",
    "Village of Anaktuvuk Pass (AK)": "352",
    "Village of Aniak (AK)": "355",
    "Village of Atmautluak (AK)": "360",
    "Village of Bill Moore's Slough (AK)": "365",
    "Village of Chefornak (AK)": "373",
    "Village of Clarks Point (AK)": "386",
    "Village of Crooked Creek (AK)": "389",
    "Village of Dot Lake (AK)": "393",
    "Village of Iliamna (AK)": "423",
    "Village of Kalskag (AK)": "430",
    "Village of Kaltag (AK)": "431",
    "Village of Kotlik (AK)": "449",
    "Village of Lower Kalskag (AK)": "459",
    "Village of Ohogamiut (AK)": "494",
    "Village of Red Devil (AK)": "518",
    "Village of Sleetmute (AK)": "535",
    "Village of Solomon (AK)": "536",
    "Village of Stony River (AK)": "540",
    "Village of Venetie (See Native Village of Venetie Tribal Government) (AK)": "562",
    "Village of Wainwright (AK)": "564",
    "Wrangell Cooperative Association (AK)": "567",
    "Yakutat Tlingit Tribe (AK)": "568",
    "Yupiit of Andreafski (AK)": "353",
    "Poarch Band of Creeks (AL; FL)": "204",
    "Ak-Chin Indian Community (AZ)": "3",
    "Cocopah Tribe of Arizona (AZ)": "48",
    "Fort McDowell Yavapai Nation, Arizona (AZ)": "90",
    "Gila River Indian Community of the Gila River Indian Reservation, Arizona (AZ)": "93",
    "Havasupai Tribe of the Havasupai Reservation, Arizona (AZ)": "100",
    "Hopi Tribe of Arizona (AZ)": "104",
    "Hualapai Indian Tribe of the Hualapai Indian Reservation, Arizona (AZ)": "107",
    "Kaibab Band of Paiute Indians of the Kaibab Indian Reservation, Arizona (AZ)": "118",
    "Pascua Yaqui Tribe of Arizona (AZ)": "193",
    "Salt River Pima-Maricopa Indian Community of the Salt River Reservation, Arizona (AZ)": "252",
    "San Carlos Apache Tribe of the San Carlos Reservation, Arizona (AZ)": "254",
    "San Juan Southern Paiute Tribe of Arizona (AZ)": "255",
    "Tohono O'odham Nation of Arizona (AZ)": "302",
    "Tonto Apache Tribe of Arizona (AZ)": "305",
    "White Mountain Apache Tribe of the Fort Apache Reservation, Arizona (AZ)": "324",
    "Yavapai-Apache Nation of the Camp Verde Indian Reservation, Arizona (AZ)": "332",
    "Yavapai-Prescott Indian Tribe (AZ)": "333",
    "Colorado River Indian Tribes of the Colorado River Indian Reservation, Arizona and California (AZ; CA)": "51",
    "Quechan Tribe of the Fort Yuma Indian Reservation, California & Arizona (AZ; CA)": "232",
    "Fort Mojave Indian Tribe of Arizona, California & Nevada (AZ; CA; NV)": "91",
    "Zuni Tribe of the Zuni Reservation, New Mexico (AZ; NM)": "339",
    "Fort Sill Apache Tribe of Oklahoma (AZ; NM; OK)": "92",
    "Navajo Nation, Arizona, New Mexico & Utah (AZ; NM; UT)": "171",
    "Agua Caliente Band of Cahuilla Indians of the Agua Caliente Indian Reservation, California (CA)": "2",
    "Alturas Indian Rancheria, California (CA)": "6",
    "Augustine Band of Cahuilla Indians, California (CA)": "11",
    "Bear River Band of the Rohnerville Rancheria, California (CA)": "14",
    "Berry Creek Rancheria of Maidu Indians of California (CA)": "15",
    "Big Lagoon Rancheria, California (CA)": "16",
    "Big Pine Paiute Tribe of the Owens Valley (CA)": "17",
    "Big Sandy Rancheria of Western Mono Indians of California (CA)": "18",
    "Big Valley Band of Pomo Indians of the Big Valley Rancheria, California (CA)": "19",
    "Bishop Paiute Tribe (CA)": "189",
    "Blue Lake Rancheria, California (CA)": "21",
    "Bridgeport Indian Colony (CA)": "22",
    "Buena Vista Rancheria of Me-Wuk Indians of California (CA)": "23",
    "Cabazon Band of Mission Indians, California (CA)": "25",
    "Cachil DeHe Band of Wintun Indians of the Colusa Indian Community of the Colusa Rancheria, California (CA)": "26",
    "Cahto Tribe of the Laytonville Rancheria (CA)": "29",
    "Cahuilla Band of Indians (CA)": "28",
    "California Valley Miwok Tribe, California (CA)": "30",
    "Campo Band of Diegueno Mission Indians of the Campo Indian Reservation, California (CA)": "31",
    "Capitan Grande Band of Diegueno Mission Indians of California (Barona Group of Capitan Grande Band of Mission Indians of the Barona Reservation, California; Viejas (Baron Long) Group of Capitan Grande Band of Mission Indians of the Viejas Reservation, California) (CA)": "32",
    "Cedarville Rancheria, California (CA)": "35",
    "Chemehuevi Indian Tribe of the Chemehuevi Reservation, California (CA)": "36",
    "Cher-Ae Heights Indian Community of the Trinidad Rancheria, California (CA)": "37",
    "Chicken Ranch Rancheria of Me-Wuk Indians of California (CA)": "42",
    "Cloverdale Rancheria of Pomo Indians of California (CA)": "47",
    "Cold Springs Rancheria of Mono Indians of California (CA)": "50",
    "Coyote Valley Band of Pomo Indians of California (CA)": "68",
    "Dry Creek Rancheria Band of Pomo Indians, California (CA)": "74",
    "Elem Indian Colony of Pomo Indians of the Sulphur Bank Rancheria, California (CA)": "78",
    "Elk Valley Rancheria, California (CA)": "79",
    "Enterprise Rancheria of Maidu Indians of California (CA)": "81",
    "Ewiiaapaayp Band of Kumeyaay Indians, California (CA)": "82",
    "Federated Indians of Graton Rancheria, California (CA)": "83",
    "Fort Bidwell Indian Community of the Fort Bidwell Reservation of California (CA)": "87",
    "Fort Independence Indian Community of Paiute Indians of the Fort Independence Reservation, California (CA)": "88",
    "Greenville Rancheria (CA)": "95",
    "Grindstone Indian Rancheria of Wintun-Wailaki Indians of California (CA)": "96",
    "Guidiville Rancheria of California (CA)": "97",
    "Habematolel Pomo of Upper Lake, California (CA)": "98",
    "Hoopa Valley Tribe, California (CA)": "103",
    "Hopland Band of Pomo Indians, California (CA)": "105",
    "Iipay Nation of Santa Ysabel, California (CA)": "108",
    "Inaja Band of Diegueno Mission Indians of the Inaja and Cosmit Reservation, California (CA)": "109",
    "Ione Band of Miwok Indians of California (CA)": "110",
    "Jackson Band of Miwuk Indians (CA)": "113",
    "Jamul Indian Village of California (CA)": "115",
    "Karuk Tribe (CA)": "120",
    "Kashia Band of Pomo Indians of the Stewarts Point Rancheria, California (CA)": "121",
    "Kletsel Dehe Band of Wintun Indians (CA)": "64",
    "Koi Nation of Northern California (CA)": "140",
    "La Jolla Band of Luiseno Indians, California (CA)": "132",
    "La Posta Band of Diegueno Mission Indians of the La Posta Indian Reservation, California (CA)": "133",
    "Lone Pine Paiute-Shoshone Tribe (CA)": "191",
    "Los Coyotes Band of Cahuilla and Cupeno Indians, California (CA)": "141",
    "Lytton Rancheria of California (CA)": "147",
    "Manchester Band of Pomo Indians of the Manchester Rancheria, California (CA)": "149",
    "Manzanita Band of Diegueno Mission Indians of the Manzanita Reservation, California (CA)": "150",
    "Mechoopda Indian Tribe of Chico Rancheria, California (CA)": "154",
    "Mesa Grande Band of Diegueno Mission Indians of the Mesa Grande Reservation, California (CA)": "156",
    "Middletown Rancheria of Pomo Indians of California (CA)": "160",
    "Mooretown Rancheria of Maidu Indians of California (CA)": "166",
    "Morongo Band of Mission Indians, California (CA)": "167",
    "Northfork Rancheria of Mono Indians of California (CA)": "176",
    "Pala Band of Mission Indians (CA)": "192",
    "Paskenta Band of Nomlaki Indians of California (CA)": "194",
    "Pauma Band of Luiseno Mission Indians of the Pauma & Yuima Reservation, California (CA)": "196",
    "Pechanga Band of Luiseno Mission Indians of the Pechanga Reservation, California (CA)": "198",
    "Picayune Rancheria of Chukchansi Indians of California (CA)": "201",
    "Pinoleville Pomo Nation, California (CA)": "202",
    "Pit River Tribe, California (includes XL Ranch, Big Bend, Likely, Lookout, Montgomery Creek and Roaring Creek Rancherias) (CA)": "203",
    "Potter Valley Tribe, California (CA)": "209",
    "Quartz Valley Indian Community of the Quartz Valley Reservation of California (CA)": "231",
    "Ramona Band of Cahuilla, California (CA)": "235",
    "Redding Rancheria, California (CA)": "238",
    "Redwood Valley or Little River Band of Pomo Indians of the Redwood Valley Rancheria California (CA)": "239",
    "Resighini Rancheria, California (CA)": "241",
    "Rincon Band of Luiseno Mission Indians of Rincon Reservation, California (CA)": "242",
    "Robinson Rancheria (CA)": "243",
    "Round Valley Indian Tribes, Round Valley Reservation, California (CA)": "245",
    "San Pasqual Band of Diegueno Mission Indians of California (CA)": "257",
    "Santa Rosa Band of Cahuilla Indians, California (CA)": "259",
    "Santa Rosa Indian Community of the Santa Rosa Rancheria, California (CA)": "258",
    "Santa Ynez Band of Chumash Mission Indians of the Santa Ynez Reservation, California (CA)": "260",
    "Scotts Valley Band of Pomo Indians of California (CA)": "264",
    "Sherwood Valley Rancheria of Pomo Indians of California (CA)": "271",
    "Shingle Springs Band of Miwok Indians, Shingle Springs Rancheria (Verona Tract), California (CA)": "272",
    "Soboba Band of Luiseno Indians, California (CA)": "283",
    "Susanville Indian Rancheria, California (CA)": "294",
    "Sycuan Band of the Kumeyaay Nation (CA)": "296",
    "Table Mountain Rancheria (CA)": "297",
    "Tejon Indian Tribe (CA)": "298",
    "Tolowa Dee-ni' Nation (CA)": "281",
    "Torres Martinez Desert Cahuilla Indians, California (CA)": "306",
    "Tule River Indian Tribe of the Tule River Reservation, California (CA)": "307",
    "Tuolumne Band of Me-Wuk Indians of the Tuolumne Rancheria of California (CA)": "310",
    "Twenty-Nine Palms Band of Mission Indians of California (CA)": "313",
    "United Auburn Indian Community of the Auburn Rancheria of California (CA)": "314",
    "Utu Utu Gwaitu Paiute Tribe of the Benton Paiute Reservation, California (CA)": "320",
    "Wilton Rancheria, California (CA)": "326",
    "Wiyot Tribe, California (CA)": "329",
    "Yocha Dehe Wintun Nation, California (CA)": "335",
    "Yuhaaviatam of San Manuel Nation (CA)": "256",
    "Yurok Tribe of the Yurok Reservation, California (CA)": "338",
    "Timbisha Shoshone Tribe (CA; NV)": "71",
    "Washoe Tribe of Nevada & California (Carson Colony, Dresslerville Colony, Woodfords Community, Stewart Community & Washoe Ranches) (CA; NV)": "323",
    "Southern Ute Indian Tribe of the Southern Ute Reservation, Colorado (CO)": "285",
    "Ute Mountain Ute Tribe (CO; NM)": "319",
    "Mashantucket Pequot Indian Tribe (CT)": "151",
    "Mohegan Tribe of Indians of Connecticut (CT)": "165",
    "Miccosukee Tribe of Indians (FL)": "159",
    "Seminole Tribe of Florida (FL)": "266",
    "Sac & Fox Tribe of the Mississippi in Iowa (IA)": "246",
    "Omaha Tribe of Nebraska (IA; NE)": "181",
    "Ponca Tribe of Nebraska (IA; NE)": "207",
    "Winnebago Tribe of Nebraska (IA; NE)": "327",
    "Kootenai Tribe of Idaho (ID)": "131",
    "Nez Perce Tribe (ID)": "172",
    "Shoshone-Bannock Tribes of the Fort Hall Reservation (ID)": "276",
    "Coeur D'Alene Tribe (ID; MT)": "49",
    "Shoshone-Paiute Tribes of the Duck Valley Reservation, Nevada (ID; NV)": "277",
    "Pokagon Band of Potawatomi Indians, Michigan and Indiana (IN; MI)": "205",
    "Kickapoo Tribe of Indians of the Kickapoo Reservation in Kansas (KS)": "126",
    "Prairie Band Potawatomi Nation (KS)": "210",
    "Iowa Tribe of Kansas and Nebraska (KS; NE)": "111",
    "Sac & Fox Nation of Missouri in Kansas and Nebraska (KS; NE)": "247",
    "Quapaw Nation (KS; OK)": "230",
    "The Muscogee (Creek) Nation (KS; OK)": "169",
    "Wyandotte Nation (KS; OK)": "330",
    "Chitimacha Tribe of Louisiana (LA)": "44",
    "Coushatta Tribe of Louisiana (LA)": "65",
    "Jena Band of Choctaw Indians (LA)": "116",
    "Tunica-Biloxi Indian Tribe (LA)": "309",
    "Mashpee Wampanoag Tribe (MA)": "152",
    "Wampanoag Tribe of Gay Head (Aquinnah) (MA)": "322",
    "Mi’kmaq Nation (ME)": "9",
    "Houlton Band of Maliseet Indians (ME)": "106",
    "Passamaquoddy Tribe (ME)": "195",
    "Penobscot Nation (ME)": "199",
    "Bay Mills Indian Community, Michigan (MI)": "13",
    "Grand Traverse Band of Ottawa and Chippewa Indians, Michigan (MI)": "94",
    "Hannahville Indian Community, Michigan (MI)": "99",
    "Keweenaw Bay Indian Community, Michigan (MI)": "124",
    "Lac Vieux Desert Band of Lake Superior Chippewa Indians of Michigan (MI)": "136",
    "Little River Band of Ottawa Indians, Michigan (MI)": "138",
    "Little Traverse Bay Bands of Odawa Indians, Michigan (MI)": "139",
    "Match-e-be-nash-she-wish Band of Pottawatomi Indians of Michigan (MI)": "153",
    "Nottawaseppi Huron Band of the Potawatomi, Michigan (MI)": "178",
    "Saginaw Chippewa Indian Tribe of Michigan (MI)": "249",
    "Sault Ste. Marie Tribe of Chippewa Indians, Michigan (MI)": "263",
    "Lower Sioux Indian Community in the State of Minnesota (MN)": "145",
    "Minnesota Chippewa Tribe, Minnesota (Six component reservations: Bois Forte Band (Nett Lake); Fond du Lac Band; Grand Portage Band; Leech Lake Band; Mille Lacs Band; White Earth Band) (MN)": "161",
    "Prairie Island Indian Community in the State of Minnesota (MN)": "211",
    "Red Lake Band of Chippewa Indians, Minnesota (MN)": "237",
    "Shakopee Mdewakanton Sioux Community of Minnesota (MN)": "269",
    "Upper Sioux Community, Minnesota (MN; WI)": "316",
    "Eastern Shawnee Tribe of Oklahoma (MO; OK)": "77",
    "Mississippi Band of Choctaw Indians (MS; TN)": "162",
    "Assiniboine and Sioux Tribes of the Fort Peck Indian Reservation, Montana (MT)": "10",
    "Blackfeet Tribe of the Blackfeet Indian Reservation of Montana (MT)": "20",
    "Chippewa Cree Indians of the Rocky Boy's Reservation, Montana (MT)": "43",
    "Confederated Salish and Kootenai Tribes of the Flathead Reservation (MT)": "53",
    "Crow Tribe of Montana (MT)": "69",
    "Fort Belknap Indian Community of the Fort Belknap Reservation of Montana (MT)": "86",
    "Little Shell Tribe of Chippewa Indians of Montana (MT)": "597",
    "Northern Cheyenne Tribe of the Northern Cheyenne Indian Reservation, Montana (MT)": "175",
    "Turtle Mountain Band of Chippewa Indians of North Dakota (MT; ND; SD)": "311",
    "Eastern Band of Cherokee Indians (NC)": "76",
    "Spirit Lake Tribe, North Dakota (ND)": "286",
    "Three Affiliated Tribes of the Fort Berthold Reservation, North Dakota (ND)": "301",
    "Sisseton-Wahpeton Oyate of the Lake Traverse Reservation, South Dakota (ND; SD)": "278",
    "Standing Rock Sioux Tribe of North & South Dakota (ND; SD)": "289",
    "Santee Sioux Nation, Nebraska (NE)": "261",
    "Oglala Sioux Tribe (NE; SD)": "179",
    "Jicarilla Apache Nation, New Mexico (NM)": "117",
    "Kewa Pueblo, New Mexico (NM)": "123",
    "Mescalero Apache Tribe of the Mescalero Reservation, New Mexico (NM)": "157",
    "Ohkay Owingeh, New Mexico (NM)": "180",
    "Pueblo of Acoma, New Mexico (NM)": "212",
    "Pueblo of Cochiti, New Mexico (NM)": "213",
    "Pueblo of Isleta, New Mexico (NM)": "215",
    "Pueblo of Jemez, New Mexico (NM)": "214",
    "Pueblo of Laguna, New Mexico (NM)": "216",
    "Pueblo of Nambe, New Mexico (NM)": "217",
    "Pueblo of Picuris, New Mexico (NM)": "218",
    "Pueblo of Pojoaque, New Mexico (NM)": "219",
    "Pueblo of San Felipe, New Mexico (NM)": "220",
    "Pueblo of San Ildefonso, New Mexico (NM)": "221",
    "Pueblo of Sandia, New Mexico (NM)": "222",
    "Pueblo of Santa Ana, New Mexico (NM)": "223",
    "Pueblo of Santa Clara, New Mexico (NM)": "224",
    "Pueblo of Taos, New Mexico (NM)": "225",
    "Pueblo of Tesuque, New Mexico (NM)": "226",
    "Pueblo of Zia, New Mexico (NM)": "227",
    "Santo Domingo Pueblo (NM)": "123",
    "Duckwater Shoshone Tribe of the Duckwater Reservation, Nevada (NV)": "75",
    "Ely Shoshone Tribe of Nevada (NV)": "80",
    "Las Vegas Tribe of Paiute Indians of the Las Vegas Indian Colony, Nevada (NV)": "137",
    "Lovelock Paiute Tribe of the Lovelock Indian Colony, Nevada (NV)": "142",
    "Moapa Band of Paiute Indians of the Moapa River Indian Reservation, Nevada (NV)": "163",
    "Paiute-Shoshone Tribe of the Fallon Reservation and Colony, Nevada (NV)": "190",
    "Pyramid Lake Paiute Tribe of the Pyramid Lake Reservation, Nevada (NV)": "229",
    "Reno-Sparks Indian Colony, Nevada (NV)": "240",
    "Summit Lake Paiute Tribe of Nevada (NV)": "292",
    "Te-Moak Tribe of Western Shoshone Indians of Nevada (Four constituent bands: Battle Mountain Band; Elko Band; South Fork Band and Wells Band) (NV)": "299",
    "Walker River Paiute Tribe of the Walker River Reservation, Nevada (NV)": "321",
    "Winnemucca Indian Colony of Nevada (NV)": "328",
    "Yerington Paiute Tribe of the Yerington Colony & Campbell Ranch, Nevada (NV)": "334",
    "Yomba Shoshone Tribe of the Yomba Reservation, Nevada (NV)": "336",
    "Fort McDermitt Paiute and Shoshone Tribes of the Fort McDermitt Indian Reservation, Nevada and Oregon (NV; OR)": "89",
    "Confederated Tribes of the Goshute Reservation, Nevada and Utah (NV; UT)": "57",
    "Cayuga Nation (NY)": "34",
    "Oneida Indian Nation (NY)": "182",
    "Onondaga Nation (NY)": "184",
    "Saint Regis Mohawk Tribe (NY)": "251",
    "Seneca Nation of Indians (NY)": "267",
    "Shinnecock Indian Nation (NY)": "273",
    "Tonawanda Band of Seneca (NY)": "303",
    "Tuscarora Nation (NY)": "312",
    "Absentee-Shawnee Tribe of Indians of Oklahoma (OK)": "1",
    "Alabama-Quassarte Tribal Town (OK)": "5",
    "Apache Tribe of Oklahoma (OK)": "7",
    "Caddo Nation of Oklahoma (OK)": "27",
    "Cherokee Nation (OK)": "38",
    "Cheyenne and Arapaho Tribes, Oklahoma (OK)": "39",
    "Citizen Potawatomi Nation, Oklahoma (OK)": "46",
    "Comanche Nation, Oklahoma (OK)": "52",
    "Delaware Nation, Oklahoma (OK)": "72",
    "Delaware Tribe of Indians (OK)": "73",
    "Iowa Tribe of Oklahoma (OK)": "112",
    "Kaw Nation, Oklahoma (OK)": "122",
    "Kialegee Tribal Town (OK)": "125",
    "Kickapoo Tribe of Oklahoma (OK)": "127",
    "Kiowa Indian Tribe of Oklahoma (OK)": "129",
    "Miami Tribe of Oklahoma (OK)": "158",
    "Modoc Nation (OK)": "164",
    "Otoe-Missouria Tribe of Indians, Oklahoma (OK)": "187",
    "Ottawa Tribe of Oklahoma (OK)": "186",
    "Pawnee Nation of Oklahoma (OK)": "197",
    "Peoria Tribe of Indians of Oklahoma (OK)": "200",
    "Ponca Tribe of Indians of Oklahoma (OK)": "206",
    "Sac & Fox Nation, Oklahoma (OK)": "248",
    "Seneca-Cayuga Nation (OK)": "268",
    "Shawnee Tribe (OK)": "270",
    "The Chickasaw Nation (OK)": "41",
    "The Choctaw Nation of Oklahoma (OK)": "45",
    "The Osage Nation (OK)": "185",
    "The Seminole Nation of Oklahoma (OK)": "265",
    "Thlopthlocco Tribal Town (OK)": "300",
    "Tonkawa Tribe of Indians of Oklahoma (OK)": "304",
    "United Keetoowah Band of Cherokee Indians in Oklahoma (OK)": "315",
    "Wichita and Affiliated Tribes (Wichita, Keechi, Waco & Tawakonie), Oklahoma (OK)": "325",
    "Burns Paiute Tribe (OR)": "24",
    "Confederated Tribes of Siletz Indians of Oregon (OR)": "59",
    "Confederated Tribes of the Coos, Lower Umpqua and Siuslaw Indians (OR)": "56",
    "Confederated Tribes of the Grand Ronde Community of Oregon (OR)": "58",
    "Confederated Tribes of the Umatilla Indian Reservation (OR)": "60",
    "Confederated Tribes of the Warm Springs Reservation of Oregon (OR)": "61",
    "Coquille Indian Tribe (OR)": "63",
    "Cow Creek Band of Umpqua Tribe of Indians (OR)": "66",
    "Klamath Tribes (OR)": "130",
    "Narragansett Indian Tribe (RI)": "170",
    "Catawba Indian Nation (aka Catawba Tribe of South Carolina) (SC)": "33",
    "Cheyenne River Sioux Tribe of the Cheyenne River Reservation, South Dakota (SD)": "40",
    "Crow Creek Sioux Tribe of the Crow Creek Reservation, South Dakota (SD)": "70",
    "Flandreau Santee Sioux Tribe of South Dakota (SD)": "84",
    "Lower Brule Sioux Tribe of the Lower Brule Reservation, South Dakota (SD)": "143",
    "Rosebud Sioux Tribe of the Rosebud Indian Reservation, South Dakota (SD)": "244",
    "Yankton Sioux Tribe of South Dakota (SD)": "331",
    "Alabama-Coushatta Tribe of Texas (TX)": "4",
    "Kickapoo Traditional Tribe of Texas (TX)": "128",
    "Ysleta del Sur Pueblo (TX)": "337",
    "Northwestern Band of the Shoshone Nation (UT)": "177",
    "Paiute Indian Tribe of Utah (Cedar Band of Paiutes, Kanosh Band of Paiutes, Koosharem Band of Paiutes, Indian Peaks Band of Paiutes, and Shivwits Band of Paiutes) (UT)": "188",
    "Skull Valley Band of Goshute Indians of Utah (UT)": "280",
    "Ute Indian Tribe of the Uintah & Ouray Reservation, Utah (UT)": "318",
    "Chickahominy Indian Tribe (VA)": "591",
    "Chickahominy Indian Tribe--Eastern Division (VA)": "592",
    "Monacan Indian Nation (VA)": "593",
    "Nansemond Indian Nation (VA)": "594",
    "Pamunkey Indian Tribe (VA)": "590",
    "Rappahannock Tribe, Inc. (VA)": "595",
    "Upper Mattaponi Tribe (VA)": "596",
    "Confederated Tribes and Bands of the Yakama Nation (WA)": "62",
    "Confederated Tribes of the Chehalis Reservation (WA)": "54",
    "Confederated Tribes of the Colville Reservation (WA)": "55",
    "Cowlitz Indian Tribe (WA)": "67",
    "Hoh Indian Tribe (WA)": "102",
    "Jamestown S'Klallam Tribe (WA)": "114",
    "Kalispel Indian Community of the Kalispel Reservation (WA)": "119",
    "Lower Elwha Tribal Community (WA)": "144",
    "Lummi Tribe of the Lummi Reservation (WA)": "146",
    "Makah Indian Tribe of the Makah Indian Reservation (WA)": "148",
    "Muckleshoot Indian Tribe (WA)": "168",
    "Nisqually Indian Tribe (WA)": "173",
    "Nooksack Indian Tribe (WA)": "174",
    "Port Gamble S'Klallam Tribe (WA)": "208",
    "Puyallup Tribe of the Puyallup Reservation (WA)": "228",
    "Quileute Tribe of the Quileute Reservation (WA)": "233",
    "Quinault Indian Nation (WA)": "234",
    "Samish Indian Nation (WA)": "253",
    "Sauk-Suiattle Indian Tribe (WA)": "262",
    "Shoalwater Bay Indian Tribe of the Shoalwater Bay Indian Reservation (WA)": "274",
    "Skokomish Indian Tribe (WA)": "279",
    "Snoqualmie Indian Tribe (WA)": "282",
    "Spokane Tribe of the Spokane Reservation (WA)": "287",
    "Squaxin Island Tribe of the Squaxin Island Reservation (WA)": "288",
    "Stillaguamish Tribe of Indians of Washington (WA)": "291",
    "Suquamish Indian Tribe of the Port Madison Reservation (WA)": "293",
    "Swinomish Indian Tribal Community (WA)": "295",
    "Tulalip Tribes of Washington (WA)": "308",
    "Upper Skagit Indian Tribe (WA)": "317",
    "Bad River Band of the Lake Superior Tribe of Chippewa Indians of the Bad River Reservation, Wisconsin (WI)": "12",
    "Forest County Potawatomi Community, Wisconsin (WI)": "85",
    "Ho-Chunk Nation of Wisconsin (WI)": "101",
    "Lac Courte Oreilles Band of Lake Superior Chippewa Indians of Wisconsin (WI)": "134",
    "Lac du Flambeau Band of Lake Superior Chippewa Indians of the Lac du Flambeau Reservation of Wisconsin (WI)": "135",
    "Menominee Indian Tribe of Wisconsin (WI)": "155",
    "Oneida Nation (WI)": "183",
    "Red Cliff Band of Lake Superior Chippewa Indians of Wisconsin (WI)": "236",
    "Sokaogon Chippewa Community, Wisconsin (WI)": "284",
    "St. Croix Chippewa Indians of Wisconsin (WI)": "250",
    "Stockbridge Munsee Community, Wisconsin (WI)": "290",
    "Arapaho Tribe of the Wind River Reservation, Wyoming (WY)": "8",
    "Eastern Shoshone Tribe of the Wind River Reservation, Wyoming (WY)": "275",
}


class MainWindow2Controller:

    def __init__(self):
        self.window = MainWindow2Dialog()
        self.window.setWindowTitle("AFCARS XML Editor")
        self.window.fips_codes = self.get_fips_codes()
        self.window.epa_codes = self.get_epa_codes()
        self.window.reporting_periods = self.get_reporting_periods()
        self.window.report_types = self.get_report_types()
        self.window.file_type = FileType.PRODUCTION
        self.window.on_go = self.do_go

        self.window.on_close = self.save_defaults
        self.window.on_export = self.do_export

    def show(self):
        self.load_defaults()
        return self.window.show()

    def load_defaults(self):
        config = ConfigTable.get_or_none(ConfigTable.id == 1)
        if config:
            self.window.epa_code = [k for k, v in EPA_CODES.items() if v == config.epa_code][
                0] if config.epa_code else None
            self.window.fips_code = [k for k, v in FIPS_CODES.items() if v == config.fips_code][
                0] if config.fips_code else None
            self.window.reporting_period = config.reporting_period
            self.window.report_type = config.report_type
            self.window.file_type = config.file_type

    def save_defaults(self):
        config, _ = ConfigTable.get_or_create(id=1)
        config.epa_code = EPA_CODES[self.window.epa_code] if self.window.epa_code else None
        config.fips_code = FIPS_CODES[self.window.fips_code] if self.window.fips_code else None
        config.reporting_period = self.window.reporting_period
        config.report_type = self.window.report_type
        config.file_type = self.window.file_type
        config.save()

    @staticmethod
    def get_fips_codes() -> list:
        return list(FIPS_CODES.keys())

    @staticmethod
    def get_epa_codes() -> list:
        return list(EPA_CODES.keys())

    @staticmethod
    def get_reporting_periods() -> list[str]:
        return [f"{year}{period}" for year in range(2023, 2036) for period in ['A', 'B']]

    @staticmethod
    def get_report_types() -> list[str]:
        return [e.value for e in ReportType]

    @property
    def agency_code(self) -> str:
        return EPA_CODES[self.window.epa_code] if self.window.epa_code \
            else FIPS_CODES[self.window.fips_code] if self.window.fips_code \
            else None

    def do_go(self, *args, **kwargs):
        controller: ChildController = ChildController(self.window)
        controller.reporting_period = self.window.reporting_period
        controller.report_type = self.window.report_type
        controller.file_type = self.window.file_type
        controller.agency_name = self.window.fips_code if self.window.fips_code \
            else self.window.epa_code if self.window.epa_code \
            else ""
        controller.e1 = self.e1
        controller.show()

    @property
    def e1(self) -> str:
        return FIPS_CODES[self.window.fips_code] if self.window.fips_code in FIPS_CODES \
            else EPA_CODES[self.window.epa_code] if self.window.epa_code in EPA_CODES \
            else ""

    def do_export(self):
        controller: ExportController = ExportController(self.window)
        controller.e1 = self.e1
        controller.e2 = self.window.reporting_period
        controller.report_type =self.window.report_type
        controller.file_type = self.window.file_type
        controller.show()
